### ISSUE TITLE
what about the version of keras?and tensorflow?

### ISSUE THREAD

**Issue by albertyou2** [qqwweee/keras-yolo3#1]
what about the version of keras?and tensorflow?

**Comment by elliotwutingfeng** [comment]
Works well for me. I am using tensorflow-gpu.

Keras version: 2.1.5
Tensorflow version: 1.4.0-rc1

**Comment by qqwweee** [comment]
I think the latest vesion is just fine.

**Comment by tanakataiki** [comment]
For me 
Keras version: 2.1.5
Tensorflow version: 1.4.0

**Comment by albertyou2** [comment]
thanks !
