### ISSUE TITLE
problem in  retraining weights

### ISSUE THREAD

**Issue by douxiao** [qqwweee/keras-yolo3#105]
I use my own dataset to retrain the weights.  information  as fllows:

Create YOLOv3 model with 9 anchors and 1 classes.
Load weights model_data/yolo_weights.h5.
Freeze the first 249 layers of total 252 layers.
Train on 458 samples, val on 50 samples, with batch size 16.

I have changed to  one class in the voc_classes.txt file, 

However, When I tested the weights, the following questions appeared;

tensorflow.python.framework.errors_impl.InvalidArgumentError: 
Dimension 0 in both shapes must be equal, but are 1 and 18 for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [18,1024,1,1].

Can you give me some advice? Where did I go wrong during training?  many thanks!

**Comment by KUASWoodyLIN** [comment]
Create the `your_classes.txt file`, and  put your classes name in the `your_classes.txt file`.

Change the train.py file https://github.com/qqwweee/keras-yolo3/blob/master/train.py#L19
```
def _main():
    annotation_path = 'train.txt'
    log_dir = 'logs/000/'
    classes_path = 'model_data/your_classes.txt'
    anchors_path = 'model_data/yolo_anchors.txt'
    class_names = get_classes(classes_path)
```

**Comment by KUASWoodyLIN** [comment]
I pre-train well on my own dataset
did you create the annotation file?
or more information please

**Comment by 18814181500** [comment]
I encountered the same problem when runing with 2007_train.txt... .. .
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 255 for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,75], [255,1024,1,1]

**Comment by qqwweee** [comment]
Make sure model file, anchor file, class file are compatible.You forget to modify the class file path.

**Comment by douxiao** [comment]
@qqwweee Thank you for solving the problem !!! that's great !  Also, I found that using the RMSprop optimizer is better than adam .
