### ISSUE TITLE
training problem on VOC datasets?

### ISSUE THREAD

**Issue by xugaoxiang** [qqwweee/keras-yolo3#111]
Error occured when  I train on VOC 2007 datasets, 
`(yolo) longjing@FR:~/Work/yolo3/keras-yolo3$ python train.py 
Using TensorFlow backend.
2018-06-14 11:43:57.532013: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Create YOLOv3 model with 9 anchors and 20 classes.
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((1, 1, 1024, 75) vs (255, 1024, 1, 1)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((75,) vs (255,)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((1, 1, 512, 75) vs (255, 512, 1, 1)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((75,) vs (255,)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((1, 1, 256, 75) vs (255, 256, 1, 1)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((75,) vs (255,)).
  weight_values[i].shape))
Load weights model_data/yolo_weights.h5.
Freeze the first 249 layers of total 252 layers.
Train on 2251 samples, val on 250 samples, with batch size 32.
Epoch 1/30
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    _main()
  File "train.py", line 33, in _main
    train(model, annotation_path, input_shape, anchors, len(class_names), log_dir=log_dir)
  File "train.py", line 61, in train
    callbacks=[logging, checkpoint, early_stopping])
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/training.py", line 2194, in fit_generator
    generator_output = next(output_generator)
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "train.py", line 151, in data_generator
    image, box = get_random_data(annotation_lines[i], input_shape, random=True)
  File "/home/longjing/Work/yolo3/keras-yolo3/yolo3/utils.py", line 39, in get_random_data
    image = Image.open(line[0])
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/PIL/Image.py", line 2548, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/longjing/Work/yolo3/keras-yolo3/VOCdevkit/VOC2007/JPEGImages/006247.jpg\n'`

There is an '\n' follow the filename, so I change the code from
`line = annotation_line.split(' ')` 
to 
`line = annotation_line.strip().split(' ')` in file utils.py

but unfortunately, another error occured
`Load weights model_data/yolo_weights.h5.
Freeze the first 249 layers of total 252 layers.
Train on 2251 samples, val on 250 samples, with batch size 32.
Epoch 1/30
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    _main()
  File "train.py", line 33, in _main
    train(model, annotation_path, input_shape, anchors, len(class_names), log_dir=log_dir)
  File "train.py", line 61, in train
    callbacks=[logging, checkpoint, early_stopping])
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/training.py", line 2194, in fit_generator
    generator_output = next(output_generator)
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "train.py", line 151, in data_generator
    image, box = get_random_data(annotation_lines[i], input_shape, random=True)
  File "/home/longjing/Work/yolo3/keras-yolo3/yolo3/utils.py", line 104, in get_random_data
    box[:, [0,2]] = box[:, [0,2]]*nw/iw + dx
IndexError: too many indices for array`

Need help please!

**Comment by qqwweee** [comment]
See edc9041. Update the code.

**Comment by xugaoxiang** [comment]
@qqwweee , thanks, i'll check the new version.

**Comment by xugaoxiang** [comment]
@qqwweee , training failed 

`
(yolo) longjing@FR:~/Work/yolo3/keras-yolo3$ python train.py 
Using TensorFlow backend.
2018-06-15 16:07:02.816198: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Create YOLOv3 model with 9 anchors and 20 classes.
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((1, 1, 1024, 75) vs (255, 1024, 1, 1)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((75,) vs (255,)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((1, 1, 512, 75) vs (255, 512, 1, 1)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((75,) vs (255,)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((1, 1, 256, 75) vs (255, 256, 1, 1)).
  weight_values[i].shape))
/home/longjing/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py:3473: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((75,) vs (255,)).
  weight_values[i].shape))
Load weights model_data/yolo_weights.h5.
Freeze the first 249 layers of total 252 layers.
Train on 2251 samples, val on 250 samples, with batch size 32.
Epoch 1/50

14/70 [=====>........................] - ETA: 1:00:09 - loss: 4176.9674
70/70 [==============================] - 3097s 44s/step - loss: 1155.2374 - val_loss: 152.2559
Epoch 2/50
70/70 [==============================] - 2301s 33s/step - loss: 112.3896 - val_loss: 82.8359
Epoch 3/50
70/70 [==============================] - 2301s 33s/step - loss: 69.7328 - val_loss: 58.9210
Epoch 4/50
70/70 [==============================] - 2295s 33s/step - loss: 51.3632 - val_loss: 44.8716
Epoch 5/50
70/70 [==============================] - 2298s 33s/step - loss: 42.1329 - val_loss: 39.3557
Epoch 6/50
70/70 [==============================] - 2300s 33s/step - loss: 36.1224 - val_loss: 33.6627
Epoch 7/50
70/70 [==============================] - 2296s 33s/step - loss: 32.3504 - val_loss: 30.6207
Epoch 8/50
70/70 [==============================] - 2297s 33s/step - loss: 29.2803 - val_loss: 28.9223
Epoch 9/50
70/70 [==============================] - 2298s 33s/step - loss: 27.4078 - val_loss: 25.2059
Epoch 10/50
70/70 [==============================] - 2295s 33s/step - loss: 26.0083 - val_loss: 24.3438
Epoch 11/50
70/70 [==============================] - 2295s 33s/step - loss: 24.5346 - val_loss: 23.5042
Epoch 12/50
70/70 [==============================] - 2296s 33s/step - loss: 23.6518 - val_loss: 22.3092
Epoch 13/50
70/70 [==============================] - 2298s 33s/step - loss: 22.6562 - val_loss: 21.7520
Epoch 14/50
70/70 [==============================] - 2297s 33s/step - loss: 21.8993 - val_loss: 22.0111
Epoch 15/50
70/70 [==============================] - 2296s 33s/step - loss: 21.3333 - val_loss: 20.7622
Epoch 16/50
70/70 [==============================] - 2295s 33s/step - loss: 20.9301 - val_loss: 21.6414
Epoch 17/50
70/70 [==============================] - 2292s 33s/step - loss: 20.3787 - val_loss: 20.2932
Epoch 18/50
70/70 [==============================] - 2295s 33s/step - loss: 20.0510 - val_loss: 19.9879
Epoch 19/50
70/70 [==============================] - 2298s 33s/step - loss: 19.4801 - val_loss: 18.7927
Epoch 20/50
70/70 [==============================] - 2293s 33s/step - loss: 19.4649 - val_loss: 18.6275
Epoch 21/50
70/70 [==============================] - 2294s 33s/step - loss: 19.1240 - val_loss: 18.8865
Epoch 22/50
70/70 [==============================] - 2295s 33s/step - loss: 18.8103 - val_loss: 18.5175
Epoch 23/50
70/70 [==============================] - 2297s 33s/step - loss: 18.4249 - val_loss: 18.3890
Epoch 24/50
70/70 [==============================] - 2297s 33s/step - loss: 18.0232 - val_loss: 17.8910
Epoch 25/50
70/70 [==============================] - 2295s 33s/step - loss: 18.1161 - val_loss: 17.8068
Epoch 26/50
70/70 [==============================] - 2295s 33s/step - loss: 18.0863 - val_loss: 17.5407
Epoch 27/50
70/70 [==============================] - 2294s 33s/step - loss: 17.5000 - val_loss: 16.9333
Epoch 28/50
70/70 [==============================] - 2294s 33s/step - loss: 17.4861 - val_loss: 17.3210
Epoch 29/50
70/70 [==============================] - 2294s 33s/step - loss: 17.3445 - val_loss: 17.2443
Epoch 30/50
70/70 [==============================] - 2291s 33s/step - loss: 17.1904 - val_loss: 17.0043
Epoch 31/50
70/70 [==============================] - 2290s 33s/step - loss: 16.9701 - val_loss: 16.6228
Epoch 32/50
70/70 [==============================] - 2293s 33s/step - loss: 16.9149 - val_loss: 17.3430
Epoch 33/50
70/70 [==============================] - 2292s 33s/step - loss: 16.4950 - val_loss: 16.4003
Epoch 34/50
70/70 [==============================] - 2290s 33s/step - loss: 16.9319 - val_loss: 17.0047
Epoch 35/50
70/70 [==============================] - 2292s 33s/step - loss: 16.8107 - val_loss: 16.5966
Epoch 36/50
70/70 [==============================] - 2290s 33s/step - loss: 16.5467 - val_loss: 15.9689
Epoch 37/50
70/70 [==============================] - 2291s 33s/step - loss: 16.5207 - val_loss: 15.9476
Epoch 38/50
70/70 [==============================] - 2291s 33s/step - loss: 16.3984 - val_loss: 17.2077
Epoch 39/50
70/70 [==============================] - 2294s 33s/step - loss: 16.2483 - val_loss: 16.6735
Epoch 40/50
70/70 [==============================] - 2291s 33s/step - loss: 16.2678 - val_loss: 15.8414
Epoch 41/50
70/70 [==============================] - 2292s 33s/step - loss: 16.3700 - val_loss: 16.4238
Epoch 42/50
70/70 [==============================] - 2292s 33s/step - loss: 16.1733 - val_loss: 16.3775
Epoch 43/50
70/70 [==============================] - 2293s 33s/step - loss: 15.9314 - val_loss: 15.8632
Epoch 44/50
70/70 [==============================] - 2289s 33s/step - loss: 16.2085 - val_loss: 15.7369
Epoch 45/50
70/70 [==============================] - 2291s 33s/step - loss: 15.8789 - val_loss: 15.2760
Epoch 46/50
70/70 [==============================] - 2289s 33s/step - loss: 16.1046 - val_loss: 16.3972
Epoch 47/50
70/70 [==============================] - 2289s 33s/step - loss: 15.9615 - val_loss: 15.7253
Epoch 48/50
70/70 [==============================] - 2291s 33s/step - loss: 15.8841 - val_loss: 15.5983
Epoch 49/50
70/70 [==============================] - 2293s 33s/step - loss: 15.8978 - val_loss: 15.9049
Epoch 50/50
70/70 [==============================] - 2295s 33s/step - loss: 15.5977 - val_loss: 15.8063
Unfreeze all of the layers.
Train on 2251 samples, val on 250 samples, with batch size 32.
Epoch 51/100
Killed
`

**Comment by Hello526** [comment]
Hi,
Do you know the mAP of YOLOV3 on PASCAL VOC2012? I read the original text and did not mention this.
Thanks a lot!

**Comment by eastlife** [comment]
I have the some problem (in get_random_data box[:, [0,2]] = box[:, [0,2]]*nw/iw + dx IndexError: too many indices for array) when training my own dataset. Could you give me any suggestions?

**Comment by xiaotongnii** [comment]
test on VOC,appear some erro about"Mismatch between model and given anchor and class sizes"
the erro may be caused by self.yolo_model.layers[-1].output_shape[-1] != num_anchors/len(self.yolo_model.output) * (num_classes + 5) 
num_anchors =9;num_classes = 20
Any help will be appreciated
