### ISSUE TITLE
convert weights error ,anyone successed on tensorflow-1.4.0

### ISSUE THREAD

**Issue by oujieww** [qqwweee/keras-yolo3#112]
i want to run this code on tensorflow-1.4.0 ,and i convert the pre-train model weights, but some error come out:

![image](https://user-images.githubusercontent.com/13203040/41403331-31f051fe-6ff7-11e8-9a9b-392c4da2f363.png)
 
shape is None, 
![image](https://user-images.githubusercontent.com/13203040/41403363-458a45ee-6ff7-11e8-90bb-4001c1363a62.png)

anyone know this ? please ,thanks!!!

**Comment by qqwweee** [comment]
This is not an error. The output shape varies with input shape, and Keras takes it as None.
