### ISSUE TITLE
webcam

### ISSUE THREAD

**Issue by RandaKhairy** [qqwweee/keras-yolo3#118]
can we modify this code to take input from webcam instead of video??

**Comment by tanakataiki** [comment]
Input 0 integer instead of char to specify webcam

**Comment by zino299792** [comment]
> Input 0 integer instead of char to specify webcam

I changed line 55 in yolo_video.py into 
`"--input", nargs='?', type=**int**, required=False, default='./path2your_video'`

and run `python yolo_video.py --input 0`, still got the error `Couldn't open webcam or video`
