### ISSUE TITLE
key error may occur 

### ISSUE THREAD

**Issue by swagger2016** [qqwweee/keras-yolo3#12]
Thanks for your nice work, there might exist some tiny flaw in model.py files when I exam the model summry:
 
input = Input(shape=(416,416,3))
model = yolo_body(input, 9, 80)
model.summary()

it will have key error about dict 
so I changed it :
    kk = None
    try:
        kk = kwargs['strides']
    except:
        kk = None
    #some mistake here
    darknet_conv_kwargs['padding'] = 'VALID' if  kk==(2,2) else 'SAME'
and it works
I hope it will helpful

**Comment by qqwweee** [comment]
I had found that, and it will be fixed later. Thanks all the same.
