### ISSUE TITLE
python yolo.py 

### ISSUE THREAD

**Issue by Amerry-c** [qqwweee/keras-yolo3#13]
when i use 'python yolo.py',it will remind me to 'Input image filename:',but when i input the image filename(like dog.jpg),it will occur 'NameError: name 'dog' is not defined'.can you help me?thank you. @tanakataiki @qqwweee

**Comment by tanakataiki** [comment]
Did you input ./dog jpg？
If you input dog.jpg it may cause problem.
If any other cause,  print screen please

**Comment by qqwweee** [comment]
Add quotes '' like 'dog.jpg' on Python2.

**Comment by Amerry-c** [comment]
@qqwweee @tanakataiki Thank you so much for your help,i sloved this problem by 'dog.jpg' cause i use python2.
