### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by nykabhishek** [qqwweee/keras-yolo3#14]
The following error is shown while converting yolov3.weights to h5 format. How can I solve this?

#### Traceback (most recent call last):
 File "convert.py", line 237, in <module>
    _main(parser.parse_args())
  File "convert.py", line 134, in _main
    buffer=weights_file.read(weights_size * 4))

**Comment by tanakataiki** [comment]
It maybe caused by mismatching cfg and .h file with yolo architecture.
If there is any update in repo or architecture it wont be useful.

**Comment by VoNhatVinh** [comment]
I fix by change the Input channel "input_layer = Input(shape=(None, None, 3))". I change 3 to 1, because I run darknet with 1 channel
