### ISSUE TITLE
Framerate performance drop: commit #6

### ISSUE THREAD

**Issue by elliotwutingfeng** [qqwweee/keras-yolo3#16]
9ef8628f8583bc7494eeab1519f2ef2dd16fff0d

Hi, thanks for the awesome repo. :grinning: 
I am currently using this repo to process video, and I noticed that commit #6 caused the framerate to drop by 1/3 on average as compared to commit #5. Is it because of the ZeroPadding2D fix?

**Comment by qqwweee** [comment]
I did a test roughly, and the time to detect one image is almost the same.
The revision does not increase the calculation. Check the input size of preprocessed image and see if two versions have difference.

**Comment by xxmarl** [comment]
Hi qqwweee, nice work!
I'm wondering what frame rate do you get? When I run this repo I cannot get anywhere close to the performance of original implementation of YOLOv3. Is it even possible to reach similar speed with keras?

**Comment by qqwweee** [comment]
I am working on GPU Tesla K40m. The original C version runs at 0.1s per image, the keras version 0.2s.
C is faster than Python (tensorflow or keras). But I do not know how big this gap is, and how to narrow the gap.

**Comment by tanakataiki** [comment]
@qqwweee 
Actually yolo_vide.py capture image via opencv an conver cv2 to PILonce the detection is done, then convert PIL to cv2. This work reduce a frame rate a bit, but not so much. 
This is not the ideal solution but the easiest way to speed  up is to change BICUBIC to LINEAR ( resizing method)
