### ISSUE TITLE
Mismatch between model and given anchor and class sizes

### ISSUE THREAD

**Issue by damvantai** [qqwweee/keras-yolo3#165]
My error occur when i use model tiny yolo?  Error in `yolo.py`
```
---> 35         self.boxes, self.scores, self.classes = self.generate()
     36 
     37     def _get_class(self):

~/Documents/Object_Detection/keras-yolo3/yolo.py in generate(self)
     66             assert self.yolo_model.layers[-1].output_shape[-1] == \
     67                 num_anchors/len(self.yolo_model.output) * (num_classes + 5), \
---> 68                 'Mismatch between model and given anchor and class sizes'
     69 
     70         print('{} model, anchors, and classes loaded.'.format(model_path))

AssertionError: Mismatch between model and given anchor and class sizes
```

**Comment by nggih** [comment]
What is the solution to this problem?

**Comment by ibrsmith** [comment]
I'm having this issue too, has anyone found a solution? Thanks!

**Comment by ibrsmith** [comment]
> 
> 
> I'm having this issue too, has anyone found a solution? Thanks!

For anyone reading this in the future: I found that if I rename tiny_yolo_anchors.txt to just yolo_anchors.txt the error does not occur.

**Comment by dawnknight** [comment]
this might help
https://github.com/allanzelener/YAD2K/issues/2

**Comment by yunyao01** [comment]
"anchors_path": 'model_data/tiny_yolo_anchors.txt',

**Comment by xiaotongnii** [comment]
change  "classes_path": 'model_data/coco_classes.txt', to  "classes_path": 'model_data/voc_classes.txt',
appear similar erro;
if wanting to  ues  "classes_path": 'model_data/voc_classes.txt',how to match between model and given anchor and class sizes.
any aply will be appreacited.

**Comment by 1994Kyle** [comment]
> My error occur when i use model tiny yolo? Error in `yolo.py`
> 
> ```
> ---> 35         self.boxes, self.scores, self.classes = self.generate()
>      36 
>      37     def _get_class(self):
> 
> ~/Documents/Object_Detection/keras-yolo3/yolo.py in generate(self)
>      66             assert self.yolo_model.layers[-1].output_shape[-1] == \
>      67                 num_anchors/len(self.yolo_model.output) * (num_classes + 5), \
> ---> 68                 'Mismatch between model and given anchor and class sizes'
>      69 
>      70         print('{} model, anchors, and classes loaded.'.format(model_path))
> 
> AssertionError: Mismatch between model and given anchor and class sizes
> ```

I think you should change your model path to the path of the weight files(h5 file) you have trained in yolo.py.I tried,and it works.

**Comment by GGDRriedel** [comment]
I have the same error. I retrained with my own classes and input, 9 in total, and I get a missmatch error. 

I suspect it's something with the model not being loaded correctly as my model output shape after loading the one I trained myself is (None,Nine,None,255). 

No clue how to fix this though.

**Comment by yquemener** [comment]
If you have to use different classes than the default ones, the current script will ignore the `--classes` argument, leading to this error. There is a fix in this pull request https://github.com/qqwweee/keras-yolo3/pull/301

You will need to use `--classes_path` instead of `--classes` and it should work.

**Comment by YTMartian** [comment]
that's maybe you modified the yolov3.cfg file

**Comment by chsmile123** [comment]
Please make sure that yolov3.cfg is not modified firstly. Then you can use convert.py to make a file called yolo.h5. I have tried. It is ok.

**Comment by bikramb98** [comment]
@yquemener Using `--classes_path` gives invalid arguments error. Any idea how to get around this?

**Comment by yquemener** [comment]
@bikramb98 Have you applied this patch? https://github.com/qqwweee/keras-yolo3/pull/301
