### ISSUE TITLE
mAP metric

### ISSUE THREAD

**Issue by desmanda** [qqwweee/keras-yolo3#166]
Hi, 
Can anyone tell me how to calculate the mAP?
Should it be calculated before or after the non_max_suppresion to the predicted boxes?
thanks!

**Comment by HulkMaker** [comment]
Same question！！ any one test it?

**Comment by desmanda** [comment]
hey,
the mAP should be calculated after the non_max_suppression. Try to follow the Pascal VOC challenge [paper](http://host.robots.ox.ac.uk/pascal/VOC/pubs/everingham10.pdf) to calculate it.

**Comment by Deepcong2019** [comment]
Maybe you can look look this https://github.com/Deepcong2019/yolov3.keras
