### ISSUE TITLE
OOM  after training and before saving the weights 

### ISSUE THREAD

**Issue by OverFlow7** [qqwweee/keras-yolo3#169]
Hello, i'am trying to train yolo3 on a custom dataset, but at the end of the training i get the following error:

 

> 2018-07-11 07:26:06.760834: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at cwise_ops_common.cc:70 : Resource exhausted: OOM when allocating tensor with shape[32,32,416,416] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> Traceback (most recent call last):
>   File "train_rifle.py", line 190, in <module>
>     _main()
>   File "train_rifle.py", line 84, in _main
>     callbacks=[logging, checkpoint, reduce_lr, early_stopping])
>   File "/home/florian/anaconda2/envs/py36/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "/home/florian/anaconda2/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1426, in fit_generator
>     initial_epoch=initial_epoch)
>   File "/home/florian/anaconda2/envs/py36/lib/python3.6/site-packages/keras/engine/training_generator.py", line 191, in fit_generator
>     class_weight=class_weight)
>   File "/home/florian/anaconda2/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1220, in train_on_batch
>     outputs = self.train_function(ins)
>   File "/home/florian/anaconda2/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2661, in __call__
>     return self._call(inputs)
>   File "/home/florian/anaconda2/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2631, in _call
>     fetched = self._callable_fn(*array_vals)
>   File "/home/florian/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1454, in __call__
>     self._session._session, self._handle, args, status, None)
>   File "/home/florian/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,32,416,416] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
>          [[Node: leaky_re_lu_1/LeakyRelu/Maximum = Maximum[T=DT_FLOAT, _class=["loc:@training_1/Adam/gradients/batch_normalization_1/cond/Merge_grad/cond_grad"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](leaky_re_lu_1/LeakyRelu/mul, batch_normalization_1/cond/Merge)]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
>          [[Node: training_1/Adam/gradients/add_3/add_grad/Shape_1/_9593 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5060_training_1/Adam/gradients/add_3/add_grad/Shape_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 

batch_size is 1 so i can't go lower than that, any idea what might be causing this OOM ?

**Comment by gittigxuy** [comment]
@OverFlow7 ,reduce the epoch,I change the freeze epoch to 2,and unfreeze epoch to 3,Thus ,the total epoch is 5 and it could be trained

**Comment by OverFlow7** [comment]
I didn't notice there was two stages (frozen and unfrozen layers) so the batch_size for the unfrozen stage was still 32 , causing the oom.

Thanks @gittigxuy

**Comment by karthika95** [comment]
@OverFlow7
i am new to deep learning. can you explain the cause of this error. I got this error while training for the VOC dataset.
