### ISSUE TITLE
Success using single GPU, failed using multi GPU

### ISSUE THREAD

**Issue by adisis** [qqwweee/keras-yolo3#170]
I'm success when running with single GPU. But when I tried using dual GPU it has error 

2018-07-11 19:43:51.355949: F tensorflow/stream_executor/cuda/cuda_dnn.cc:444] could not convert BatchDescriptor {count: 0 feature_map_count: 32 spatial: 416 416  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX} to cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)

configuration 
   os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'
   gpu_num=2

environment 
   CUDA 9.0
   CUDNN 7.0.5
   TF 1.5.0
   keras 2.2.0

suspect processing under this script 
        out_boxes, out_scores, out_classes = self.sess.run(
            [self.boxes, self.scores, self.classes],
            feed_dict={
                self.yolo_model.input: image_data,
                self.input_image_shape: [image.size[1], image.size[0]],
                K.learning_phase(): 0
            })

**Comment by tanakataiki** [comment]
See #151

**Comment by pageedward** [comment]
@adisis Do you have the problem Not running on GPU even though the GPU memory has been taken up. but it can run on cpu? how do u fix it? following author's config?

**Comment by adisis** [comment]
there's no issue using CPU by following author's config.
maybe some issue when installation of cuda is not smooth.
