### ISSUE TITLE
python train.py occured unexpected keyword argument 'skip_mismatch' error

### ISSUE THREAD

**Issue by Amerry-c** [qqwweee/keras-yolo3#18]
hi, @tanakataiki ,when I execute 'python train.py' in my personal notebook is able to train,but using the same method on the server causes the following error:
Traceback (most recent call last):
  File "train.py", line 158, in <module>
    _main()
  File "train.py", line 35, in _main
    load_pretrained=True, freeze_body=True)
  File "train.py", line 122, in create_model
    model_body.load_weights(weights_path, by_name=True, skip_mismatch=True)
TypeError: load_weights() got an unexpected keyword argument 'skip_mismatch'
Is this related to the python version or other questions？

**Comment by qqwweee** [comment]
It seems like a problem about Keras version. The testing environment is Keras 2.1.5.

**Comment by Amerry-c** [comment]
@qqwweee ,thanks for your help,it sloved my problem.

**Comment by akmal4244** [comment]
> It seems like a problem about Keras version. The testing environment is Keras 2.1.5.

Thank you, solve my problem.

**Comment by cyberjam** [comment]
Thank you so much!!

**Comment by hilaPollak** [comment]
I use keras version 2.4.3
and tensorflow version 2.0.0 and still not run- what can I do?
