### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1379040 values, but the requested shape requires a multiple of 12675

### ISSUE THREAD

**Issue by Ssrzbao** [qqwweee/keras-yolo3#20]
when I run train.py, I meet the problem like title. Can you teach me how to solve the problem? what's the meaning of multiple of 12675? Thank you.

**Comment by qqwweee** [comment]
1379040 = 32*13*13*3*(5+80)
12675 = 1*13*13*3*(5+20)
The dims are batch, height, width, num_anchors, (5+num_classes).

**Comment by KeeleyYu** [comment]
@Ssrzbao Have you solved this problem? I met it too.
