### ISSUE TITLE
the question about Requirement

### ISSUE THREAD

**Issue by wzjiang** [qqwweee/keras-yolo3#21]
Could you list the specific requirements just like the vision about OpenCV， Python， Tensorflow-gpu， Keras and so on. Thank your great work.

**Comment by tanakataiki** [comment]
I use python3.5 cv3.4 tensorflow1.6 keras2.1.5. Other required environments wouldn't affect much, I think.

**Comment by wzjiang** [comment]
thank you

**Comment by geiszla** [comment]
I also needed h5py to be installed.

I compiled a requirements.txt from the above dependencies, which works fine for converting the model (I didn't try to run it, so that may require more dependencies):
[requirements.txt](https://github.com/qqwweee/keras-yolo3/files/2643798/requirements.txt)

**Comment by dek8v5** [comment]
this solves my problem as well. That requirement.txt does help. Thanks
