### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal

### ISSUE THREAD

**Issue by asd51731** [qqwweee/keras-yolo3#211]
I use the my own data to train the model, and use model.save_weights or model.save to save the weights or model. But when I use the weight or model I tried in yolo_video.py and changed the model_path in yolo.py, it report error of below :  

ValueError: Dimension 0 in both shapes must be equal, but are 1 and 21. Shapes are [1,1,1024,255] and [21,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [21,1024,1,1].  
From the error report, it occured when load the model (use the all model not the weight), do you meet the same error, or can you give me some help? 

Thanks.

**Comment by codecookinging** [comment]
hi，i met  the same error when i test my model ,can you share me the solution?

**Comment by AntoineMath** [comment]
Same problem, anybody resolved it ?

**Comment by xinyuegtxy** [comment]
@asd51731 the same problem, anybody resolved it?

**Comment by oushu1litong1** [comment]
Make sure the 2 classes_path variables in train.py and yolo.py are the same as

**Comment by RiaanLab** [comment]
Same issue.

**Comment by zahidzqj** [comment]
Same issue,and how to resolved it?

oh,我用错了类对应的txt文本。
