### ISSUE TITLE
Detection issue

### ISSUE THREAD

**Issue by vicdf** [qqwweee/keras-yolo3#24]
I followed your instruction to run 'python yolo.py' , then I typed the test image's name. It went wrong. Like this:
![2018-05-03 16-27-37](https://user-images.githubusercontent.com/26131091/39566828-74c65006-4eef-11e8-83cb-91404be0c0d3.png)
@qqwweee

**Comment by qqwweee** [comment]
The problem is probably that, Python2 uses integer division as default, 2/3 is seen as 0.
