### ISSUE TITLE
Error in train.py

### ISSUE THREAD

**Issue by jindongwang** [qqwweee/keras-yolo3#25]
I got the problem:
$ python train.py
File "train.py", line 125
[*model_body.output, *y_true])
^
SyntaxError: invalid syntax

I have read the other issues #22 but got nothing helpful. I have modified my train.txt.

**Comment by yinggo** [comment]
Could you tell more detail about how to modify the code? I also meet the same error, not solved yet.

**Comment by tanakataiki** [comment]
If you download yoloweight from my drive, you dont have to modify anything.

**Comment by wang-tf** [comment]
If using python3 instead of python, you will fix this problem. I don't know why, but it works.

**Comment by Mrlawrance** [comment]
using python3.6 train.py
