### ISSUE TITLE
Error with leaky_relu

### ISSUE THREAD

**Issue by jindongwang** [qqwweee/keras-yolo3#26]
Hi there, I got the following error:
![qq 20180503175832](https://user-images.githubusercontent.com/6158206/39570681-a871f386-4efb-11e8-9635-57a4b7d3a5c5.png)

I'm using Tensorflow 1.5.0. Is this OK?

**Comment by mayidu** [comment]
hello, I also encountered the same problem， Can you tell me how to solve it? Thanks!
I use tensorflow 1.2.1
keras 2.2.0

**Comment by jindongwang** [comment]
Sorry I can't help you. I'm already out of object detection problems...
