### ISSUE TITLE
Mismatch between model and given...

### ISSUE THREAD

**Issue by lightning20** [qqwweee/keras-yolo3#277]
Tried to re-train the model with one class with 200 echo. After that using the same class and anchor files for detection. But it give error in 78 lines in yolo.py as below.
AssertionError: Mismatch between model and given anchor and class sizes
I tried to debug, but not sure the meaning of that line, also the value 255 is a bit strange.
<img width="775" alt="untitled" src="https://user-images.githubusercontent.com/15936897/48463738-0b39da00-e818-11e8-9f4b-d693c72acb07.png">

**Comment by ylxdzsw** [comment]
Hi, did you solve it? I have the exactly same problem.

**Comment by DiJester** [comment]
me too

**Comment by younghuvee** [comment]
care about the number of filters

**Comment by Emma0928** [comment]
me too

**Comment by YTMartian** [comment]
that's because you modified the yolov3.cfg file.

**Comment by huang-yu-t** [comment]
Excuse,I would like to know how did you solve it?
