### ISSUE TITLE
Error with Convert the Darknet YOLO model to a Keras model.

### ISSUE THREAD

**Issue by Rorschaaaach** [qqwweee/keras-yolo3#28]
thanks for you work!
i notice that when i try to convert darknet yolo model to a keras model, there is an error

![mpbl xxz 7 d2_ xt9 p 6](https://user-images.githubusercontent.com/37372729/39574940-69af9652-4f0b-11e8-9d20-1fe0218de5e0.png)
so did the project  miss something or something i forget？

**Comment by qqwweee** [comment]
The script requires 3 parameters. You forgot config_path.

**Comment by Rorschaaaach** [comment]
em。。。I just follow your step，i do not understand what should i do to make it usefull。

**Comment by qqwweee** [comment]
Compare yours and this one, you forgot `yolov3.cfg`.
`python convert.py yolov3.cfg yolov3.weights model_data/yolo.h5`

**Comment by Rorschaaaach** [comment]
.....what a stupid mistake。Thanks for your patient！！！
