### ISSUE TITLE
Should I change the input shape?

### ISSUE THREAD

**Issue by quhutunlang** [qqwweee/keras-yolo3#290]
I find that the input shape is (416, 416, 3), but my data is (1080, 1920, 3). Should I change the input shape from (416, 416, 3) to (1088, 1920, 3)?

**Comment by YunYang1994** [comment]
yes you can if don't mind compute cost. hope it helps you https://github.com/YunYang1994/tensorflow-yolov3

**Comment by quhutunlang** [comment]
Thank you very much. But I think the performance of official yolov3 is better. https://pjreddie.com/darknet/yolo/

**Comment by 404hasbeenfound** [comment]
Because the offical yolov3 is running in the darknet,which is coding with C ,but this is running in the keras,which is coding with python.And the python program language is based on C.
