### ISSUE TITLE
有人知道怎么在这个工程中画出P-R曲线和Loss曲线吗？

### ISSUE THREAD

**Issue by ghost** [qqwweee/keras-yolo3#309]

**Comment by HoldYourFire** [comment]
因为尤其是P-R曲线，是很重要的评价指标，还请大神解答，不胜感激

**Comment by HoldYourFire** [comment]
有人知道吗？求解答

**Comment by ancientghost** [comment]
You can use tensorboard:  
    `tensorboard --logdir=./logs/`
Open your Web Browser and then input `http://6cb5af0f1acc:6006`(might be different).

**Comment by ldsyou92** [comment]
> You can use tensorboard:
> `tensorboard --logdir=./logs/`
> Open your Web Browser and then input `http://6cb5af0f1acc:6006`(might be different).

How shall I use tensorboard? In python or command line?

**Comment by ancientghost** [comment]
@ldsyou92 command line

**Comment by plsong** [comment]
put http://your computer name :6006:6006 in yourBrowse
