### ISSUE TITLE
Can't run YOLO3 on GPU RTX 2080 TI ?

### ISSUE THREAD

**Issue by luan1412167** [qqwweee/keras-yolo3#312]
Hi, I experimented yolo3 on GPU RTX 2080 TI. Nevertheless, it only run to the following line and stop. It doesn't produce any error but it stops at there. I experimented it with CPU and it is well. You encountered the error ?  Help me !! Thank you so much. 

# Run the yolo model
    out_scores, out_boxes, out_classes = sess.run([scores, boxes, classes], feed_dict={yolo_model.input: image_data,
K.learning_phase(): 0})

**Comment by UserStory** [comment]
change to cuda10 and cudnn7.4.2

**Comment by iamheidi** [comment]
I use 2080 too. First install nvidia 410.(If the Cuda 10 is installed automatically, cover it with 9.0.) and cuda9.0 . install all cuda9.0 patch(1,2,3,4).

**Comment by UserStory** [comment]
是这样的2080ti 最低支持 cuda9.2 （但是据说cuda9.2再2080ti上有bug）。不是yolo算法不能跑，是tensorflow 不支持 cuda 9.2以上版本，你需要自己编译tensorflow源码

At 2019-01-14 10:46:05, "iamheidi" <notifications@github.com> wrote:


I use 2080 too. First install nvidia 410.(If the Cuda 10 is installed automatically, cover it with 9.0.) and cuda9.0 . install all cuda9.0 patch(1,2,3,4).
