### ISSUE TITLE
Error in yolo_head() in model.py

### ISSUE THREAD

**Issue by dudeperf3ct** [qqwweee/keras-yolo3#336]
While testing on single image after training on VOC dataset, I encountered following errors.

In `grid = K.cast(grid, K.dtype(feats))` on [line 134](https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo3/model.py#L134), feats is a list. There is no dtype for list.  

**type(yolo_model.output) --> list**

**Error: AttributeError: 'list' object has no attribute 'dtype'** 

Screenshots of Error code attached:

![yolo_head](https://user-images.githubusercontent.com/10743098/52018678-35469280-2511-11e9-8f07-5b0ff8db7cca.png)

**Comment by apatsekin** [comment]
how do you run the test? the code looks like [original repo](https://github.com/allanzelener/YAD2K/blob/master/test_yolo.py#L109) (YAD2K)

**Comment by dudeperf3ct** [comment]
Here are the steps I followed:
1. create yolo model from trained weights
2. pass yolo_model.output to yolo_eval along with test image size, anchors and classes
3. preprocess the image and run a session to get boxes, scores and classes as output.

**Comment by khu834** [comment]
your `anchors` is a list
you need to convert it to a numpy array
`anchors = np.array(anchors).reshape(-1, 2)`

**Comment by akashkumar398** [comment]
what's the solution

**Comment by dudeperf3ct** [comment]
Check this [notebook](https://github.com/dudeperf3ct/DL_Notebooks/blob/master/Object%20Detection/Keras/object_detection_keras.ipynb).
