### ISSUE TITLE
Error while training the network

### ISSUE THREAD

**Issue by agnibrainhack** [qqwweee/keras-yolo3#337]
get_random_data(annotation_line, input_shape, random, max_boxes, jitter, hue, sat, val, proc_img)
    117         box = box[np.logical_and(box_w>1, box_h>1)] # discard invalid box
    118         if len(box)>max_boxes: box = box[:max_boxes]
--> 119         box_data[:len(box)] = box
    120 
    121     return image_data, box_data

ValueError: could not broadcast input array from shape (2,4) into shape (2,5)

**The following error appears when trying to train with custom images of size 416, 416 on tiny-yolo-v3**

**Comment by jjjj4444** [comment]
i got the same problem. did you figure it out?

**Comment by agnibrainhack** [comment]
I had the problem after tinkering with the code for a shape mismatch. The problem arises if the input txt is not in proper format
