### ISSUE TITLE
训练自己数据集，预测图片时出现问题

### ISSUE THREAD

**Issue by HaiLongEmb** [qqwweee/keras-yolo3#354]
各位大神请指教：

我使用自己训练好的模型，预测图片时出现如下情况：

![1](https://user-images.githubusercontent.com/32731062/53461283-032a4100-3a7b-11e9-9dcd-bcff9b5312a6.jpg)
![2](https://user-images.githubusercontent.com/32731062/53461294-0de4d600-3a7b-11e9-8b5a-6bfb50aca2ed.jpg)

我的数据集2000，迭代800次，最后var loss 是16.7。请问验证时有的图片出现这种情况，是训练的不好，还是yolov3.cfg文件中anchors配置的不好，请指教如何改善这种情况。

**Comment by ldfinfontainebleau** [comment]
我记得有一个计算anchor的程序，你可以搜搜。
你试试在yolo.py里面把score的阈值定高点就可以把分数低的框去掉了。
个人看法，yolo略微不准也算正常。
希望对你有所帮助。

**Comment by HaiLongEmb** [comment]
@ldfinfontainebleau  感谢你的回答，提高score的阈值是可以去掉一些框，但还是有高分值的两个框重叠情况出现。我对anchor的理解还不深入，请分享一个你宝贵的经验，并且如果你找到了计算anchor的程序麻烦发给我一下。  
感谢你的帮助。

**Comment by ldfinfontainebleau** [comment]
> @ldfinfontainebleau 感谢你的回答，提高score的阈值是可以去掉一些框，但还是有高分值的两个框重叠情况出现。我对anchor的理解还不深入，请分享一个你宝贵的经验，并且如果你找到了计算anchor的程序麻烦发给我一下。
> 感谢你的帮助。

https://github.com/ldfinfontainebleau/YOLO_compute_anchor 我刚上传的文件，你可以试试看。
  祝好！

**Comment by ancientghost** [comment]
This problem can be solved by __non-maximum-supression__. It has been already embedded,
https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo3/model.py#L218

Perhaps, what you need is to modify the threshold
https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo.py#L99

**Comment by HaiLongEmb** [comment]
@ldfinfontainebleau 你好，YOLO_compute_anchor 我看了，有个问题想请教，kmeans是自己实现的K聚类吗？网上的版本比较多不知道哪个适用。并且yolov3.cfg中的anchor应该如何修改，能指导一下吗？                  
期待大神的指导

**Comment by GreenVegetables123** [comment]
居然跟我一样在检测安全帽，哈哈

**Comment by CherishineNi** [comment]
@HaiLongEmb 请问可以分享一下您测试图片的脚本吗？邮箱1376144896@qq.com  谢谢

**Comment by HaiLongEmb** [comment]
@CherishineNi  我给你发一下连接吧，https://github.com/Cartucho/mAP，我用这个测试准确度的。

**Comment by ldfinfontainebleau** [comment]
@HaiLongEmb 就我的理解来说anchor的计算就是简单的对训练数据聚类，然后发现这些训练数据预测概率最大的几个预测框。之前我没注意，这个项目有个文件kmeans.py就是计算anchor的。通过运行这个项目的这个程序得出几个anchor，然后覆盖anchors.txt里面就行。
顺颂商祺

**Comment by CherishineNi** [comment]
> @HaiLongEmb 就我的理解来说anchor的计算就是简单的对训练数据聚类，然后发现这些训练数据预测概率最大的几个预测框。之前我没注意，这个项目有个文件kmeans.py就是计算anchor的。通过运行这个项目的这个程序得出几个anchor，然后覆盖anchors.txt里面就行。
> 顺颂商祺

那请问kmeans.py 运行后精准度在74%左右，算合理吗？如何提高anchors的准确度呢？

**Comment by ldfinfontainebleau** [comment]
@CherishineNi 我个人觉得74%可以接受，其实我觉得anchors无法特别精确，他本身就是一个提供预测候选框，对检测结果影响有限，不用花太多精力去关注。

**Comment by lukaisheng1203** [comment]
你好，你是怎么修改代码训练自己的数据的啊，为什么我训练自己的数据检测时什么都检测不到啊

**Comment by lcltopismine** [comment]
改一下score和iou，看看如何，也可能你train的有问题，有些情况下不要用预处理权重

**Comment by CherishineNi** [comment]
> 改一下score和iou，看看如何，也可能你train的有问题，有些情况下不要用预处理权重

请问预处理的权重是通过covert.py 生成的yolo_weights.h5这个权重文件吗？什么样的情况下不要用预处理的权重？自己的数据集只用3000张图片，检测目标有3类

**Comment by lcltopismine** [comment]
> > 改一下score和iou，看看如何，也可能你train的有问题，有些情况下不要用预处理权重
> 
> 请问预处理的权重是通过covert.py 生成的yolo_weights.h5这个权重文件吗？什么样的情况下不要用预处理的权重？自己的数据集只用3000张图片，检测目标有3类

要用convert.py，不过如果你的预测类和这个repo的预训练类差得很大，我觉得就不要用预训练权重了。类似的讨论在issues里面也有的

**Comment by CherishineNi** [comment]
> > > 改一下score和iou，看看如何，也可能你train的有问题，有些情况下不要用预处理权重
> > 
> > 
> > 请问预处理的权重是通过covert.py 生成的yolo_weights.h5这个权重文件吗？什么样的情况下不要用预处理的权重？自己的数据集只用3000张图片，检测目标有3类
> 
> 要用convert.py，不过如果你的预测类和这个repo的预训练类差得很大，我觉得就不要用预训练权重了。类似的讨论在issues里面也有的

我要预测的是人person和头盔helmet

**Comment by xqtbox** [comment]
ancientghost  多谢🙏大神说的是对的， 楼主搜一下 ：非极大值抑制(Non-Maximum Suppression) 就懂了

**Comment by Breezewrf** [comment]
> This problem can be solved by **non-maximum-supression**. It has been already embedded,
> https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo3/model.py#L218
> 
> Perhaps, what you need is to modify the threshold
> https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo.py#L99

Actually, I finish this problem with higher the "score" in yolo.py, sucessfully, good luck to others
