### ISSUE TITLE
How to run on CPU?

### ISSUE THREAD

**Issue by canyilmaz90** [qqwweee/keras-yolo3#383]
I have GPU, I'm running the code on it very well, but I want to see how does it work on CPU. Is there a "no gpu" option?

**Comment by bluesy7585** [comment]
I think it depends on tensorflow version. install cpu version tensorflow instead of tensorflow-gpu.

**Comment by SaltyFishQF** [comment]
Just add two lines if u use a gpu version of tensorflow
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"]="-1"
```
