### ISSUE TITLE
没有resize的话你有检测到物体么？我用原尺寸训练无法检测物体，但是换成和图片一样的尺寸可以检测但是效果很差> 请问训练我自己数据的时候，输入图像的尺寸需要统一成416*416吗？

### ISSUE THREAD

**Issue by KowalskiWang** [qqwweee/keras-yolo3#386]
> 请问训练我自己数据的时候，输入图像的尺寸需要统一成416*416吗？

我没有resize

_Originally posted by @CherishineNi in https://github.com/qqwweee/keras-yolo3/issues/254#issuecomment-476023095_

**Comment by CherishineNi** [comment]
我没有resize，但loss到17就降不下去
