### ISSUE TITLE
error with yolo.py: InvalidArgumentError

### ISSUE THREAD

**Issue by AlphaRalph** [qqwweee/keras-yolo3#40]
When I run the python yolo.py an InvalidArgumentError occurs:

![invalidargumenterror](https://user-images.githubusercontent.com/37446822/39746079-95da0c0c-52a9-11e8-9055-3f51dad66c11.png)

**Comment by qqwweee** [comment]
It seems like `model.h5` and `classes.txt` do not match. Check it.

**Comment by AlphaRalph** [comment]
You were right!
Finally it worked

Would be nice to specify the classes.txt filepath in the call: python yolo.py [parameters]
