### ISSUE TITLE
ValueError in convert.py

### ISSUE THREAD

**Issue by AlphaRalph** [qqwweee/keras-yolo3#41]
While converting the official tiny-YoloV3 (https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-tiny.cfg) the following error occurs:

![valueerror](https://user-images.githubusercontent.com/37446822/39752025-7893afc0-52ba-11e8-9eb9-d11b5fd64519.png)

**Comment by qqwweee** [comment]
It is not supported. Maybe add later.

**Comment by AlphaRalph** [comment]
Ok, I'd love to get this feature.
For embedded use only tiny Yolo is suitable ;-)
