### ISSUE TITLE
自建数据yolov3单分类检测训练，损失在1附近就基本不下降来回走，改小学习率也没有，检测精度在0.7左右，请教有人知道这种情况的原因么？

### ISSUE THREAD

**Issue by CPP520** [qqwweee/keras-yolo3#445]
自建数据yolov3单分类检测训练，损失在1附近就基本不下降来回走，改小学习率也没有，检测精度在0.7左右，请教有人知道这种情况的原因么？

_Originally posted by @zhangcj13 in https://github.com/qqwweee/keras-yolo3/issues/254#issuecomment-484804231_

**Comment by CPP520** [comment]
请问您是怎么知道检测精度的？在下小白一个，也需要这个参数，求指教

**Comment by ghost** [comment]
请问这个问题体是如何解决的。我也是做的单类检测，检测准确率不高
