### ISSUE TITLE
Is it possible to use resnet backbone in Yolo v3?

### ISSUE THREAD

**Issue by dmadhitama** [qqwweee/keras-yolo3#449]
Is there any possibilities to use for instance resnet101 in the Yolo v3? If it is, any resource to find the .cfg and .weights file? Because when I referred to https://pjreddie.com/darknet/yolo/ there was not any resources for resnet backbone.

And I'm just curious, what is the backbone that being used in YOLOv3-320 model provided in pjreddie site?

**Comment by AlbertoSabater** [comment]
The backbone used in Yolo v3 is called Darknet-53.
To change the backbone, you should this [function](https://github.com/qqwweee/keras-yolo3/blob/master/yolo3/model.py#L46) to fit the resnet101 architecture and later load its weights.

**Comment by dmadhitama** [comment]
> The backbone used in Yolo v3 is called Darknet-53.
> To change the backbone, you should this [function](https://github.com/qqwweee/keras-yolo3/blob/master/yolo3/model.py#L46) to fit the resnet101 architecture and later load its weights.

How can I modify [this](https://github.com/qqwweee/keras-yolo3/blob/master/yolo3/model.py#L46) function so I can change the backbone? What function do I have to modify? Or do I have to make my own function to fit the resnet101?

I'm also wondering because I just found the .cfg link in the pjreddie site [here](https://pjreddie.com/darknet/imagenet/), can I use this [.cfg](https://github.com/pjreddie/darknet/blob/master/cfg/resnet101.cfg) and [.weights](https://pjreddie.com/media/files/resnet101.weights) files and then convert them to create new .h5 file contained resnet101 model, instead modify the model.py?

**Comment by AlbertoSabater** [comment]
You have to make your own function to fit the resnet101 architecture. 
The .h5 file is just to load the weights into an already built NN.

**Comment by dmadhitama** [comment]
> You have to make your own function to fit the resnet101 architecture.
> The .h5 file is just to load the weights into an already built NN.

Alright then. Thank you for the answers!

**Comment by abdelDebug** [comment]
@dmadhitama Did you find please a solution to  use resnet backbone in Yolo v3 ?

**Comment by OrjwanZaafarani** [comment]
Were you able to implement it? @dmadhitama
