### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by ghost** [qqwweee/keras-yolo3#456]
`Train on 223 samples, val on 24 samples, with batch size 32.
Epoch 1/50
2019-05-15 21:32:41.137842: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
3/6 [==============>...............] - ETA: 16s - loss: 7287.8826Traceback (most recent call last):
  File "C:\deep_learning\keras-yolo3\train.py", line 200, in <module>
    _main()
  File "C:\deep_learning\keras-yolo3\train.py", line 63, in _main
    callbacks=[logging, checkpoint])
  File "C:\Users\coody\Anaconda3\envs\tf\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\coody\Anaconda3\envs\tf\lib\site-packages\keras\engine\training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\coody\Anaconda3\envs\tf\lib\site-packages\keras\utils\data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "C:\Users\coody\Anaconda3\envs\tf\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\coody\Anaconda3\envs\tf\lib\site-packages\keras\utils\data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "C:\deep_learning\keras-yolo3\train.py", line 182, in data_generator
    image, box = get_random_data(annotation_lines[i], input_shape, random=True)
  File "C:\deep_learning\keras-yolo3\yolo3\utils.py", line 47, in get_random_data
    box = np.array([np.array(list(map(int, box.split(',')))) for box in line[1:]])
  File "C:\deep_learning\keras-yolo3\yolo3\utils.py", line 47, in <listcomp>
    box = np.array([np.array(list(map(int, box.split(',')))) for box in line[1:]])
ValueError: invalid literal for int() with base 10: ''`

`C:/deep_learning/keras-yolo3/dataset/train_dataset/DBA90206.jpg 311,707,472,842,0 351,631,452,721,0 438,473,519,563,0 420,553,557,688,0 501,446,641,607,0 602,370,759,548,0 809,436,953,603,0 709,568,862,721,0 560,609,719,781,0 506,733,643,884,0 430,845,577,978,0 686,713,848,853,0 564,888,715,1041,0 393,969,546,1120,0 610,1015,736,1159,0 465,1149,606,1287,0 612,1217,744,1345,0 709,1321,858,1461,0 798,1422,939,1542,0 829,1542,907,1674,0 877,1533,1017,1663,0 916,1673,1015,1795,0 956,1620,1097,1766,0 959,1401,1078,1530,0 967,1278,1102,1412,0 756,1095,902,1229,0 906,1116,1048,1251,0 728,912,864,1049,0 849,987,987,1129,0 849,809,982,943,0 978,936,1106,1068,0 891,690,1028,835,0 912,550,1048,697,0 1098,1718,1236,1854,0 1302,1780,1434,1903,0 1271,1675,1398,1813,0 1127,1606,1253,1734,0 1049,1499,1177,1646,0 1131,1416,1272,1546,0 1218,1497,1361,1642,0 1355,1564,1487,1704,0 1414,1670,1538,1782,0 1109,1311,1241,1437,0 1237,1344,1376,1482,0 1353,1417,1484,1552,0 1084,1168,1215,1303,0 1218,1217,1346,1358,0 1373,1272,1505,1405,0 1333,1157,1460,1283,0 1207,1089,1332,1215,0 1042,1032,1195,1173,0 1201,962,1328,1090,0 1314,1030,1448,1151,0 991,791,1133,925,0 1109,837,1251,974,0 1313,899,1434,1020,0 1046,655,1184,788,0 1165,712,1285,842,0 1280,780,1410,919,0 1070,524,1203,645,0 1223,579,1352,710,0 1342,611,1466,749,0 977,282,1119,443,0 1125,223,1273,374,0 1104,392,1231,526,0 1208,457,1343,585,0 1278,311,1413,455,0 1311,177,1456,309,0 1461,160,1599,300,0 1408,328,1536,471,0 1354,458,1491,604,0 1484,435,1607,574,0 1616,347,1748,478,0 1705,436,1815,579,0 1615,479,1735,610,0 1456,565,1567,692,0 1581,611,1714,751,0 1712,569,1829,701,0 1454,701,1590,836,0 1417,817,1554,949,0 1576,757,1689,881,0 1687,733,1788,862,0 1769,843,1891,973,0 1540,873,1681,1002,0 1437,950,1577,1074,0 1642,951,1770,1077,0 1571,1005,1682,1127,0 1432,1075,1564,1204,0 1581,1123,1699,1259,0 1688,1082,1788,1212,0 1802,1030,1920,1157,0 1488,1207,1608,1333,0 1664,1189,1775,1330,0 1763,1159,1875,1298,0 1883,1137,1995,1258,0 1848,1234,1962,1353,0 1733,1260,1841,1372,0 1561,1272,1683,1407,0 1475,1368,1624,1497,0 1587,1429,1695,1557,0 1705,1394,1824,1518,0 1635,1523,1762,1654,0 1464,1482,1579,1609,0 1527,1603,1653,1714,0 1521,1710,1638,1831,0 1802,491,1909,619,0 1946,497,2059,627,0 2062,631,2179,756,0 1895,649,2011,767,0 1993,745,2117,876,0 1851,777,1968,894,0 1922,929,2035,1042,0 2012,881,2121,1008,0 1950,1019,2046,1122,0 2008,1084,2114,1200,0
C:/deep_learning/keras-yolo3/dataset/train_dataset/0009496A.jpg 311,707,472,842,0 351,631,452,721,0 438,473,519,563,0 420,553,557,688,0 501,446,641,607,0 602,370,759,548,0 809,436,953,603,0 709,568,862,721,0 560,609,719,781,0 506,733,643,884,0 430,845,577,978,0 686,713,848,853,0 564,888,715,1041,0 393,969,546,1120,0 610,1015,736,1159,0 465,1149,606,1287,0 612,1217,744,1345,0 709,1321,858,1461,0 798,1422,939,1542,0 829,1542,907,1674,0 877,1533,1017,1663,0 916,1673,1015,1795,0 956,1620,1097,1766,0 959,1401,1078,1530,0 967,1278,1102,1412,0 756,1095,902,1229,0 906,1116,1048,1251,0 728,912,864,1049,0 849,987,987,1129,0 849,809,982,943,0 978,936,1106,1068,0 891,690,1028,835,0 912,550,1048,697,0 1098,1718,1236,1854,0 1302,1780,1434,1903,0 1271,1675,1398,1813,0 1127,1606,1253,1734,0 1049,1499,1177,1646,0 1131,1416,1272,1546,0 1218,1497,1361,1642,0 1355,1564,1487,1704,0 1414,1670,1538,1782,0 1109,1311,1241,1437,0 1237,1344,1376,1482,0 1353,1417,1484,1552,0 1084,1168,1215,1303,0 1218,1217,1346,1358,0 1373,1272,1505,1405,0 1333,1157,1460,1283,0 1207,1089,1332,1215,0 1042,1032,1195,1173,0 1201,962,1328,1090,0 1314,1030,1448,1151,0 991,791,1133,925,0 1109,837,1251,974,0 1313,899,1434,1020,0 1046,655,1184,788,0 1165,712,1285,842,0 1280,780,1410,919,0 1070,524,1203,645,0 1223,579,1352,710,0 1342,611,1466,749,0 977,282,1119,443,0 1125,223,1273,374,0 1104,392,1231,526,0 1208,457,1343,585,0 1278,311,1413,455,0 1311,177,1456,309,0 1461,160,1599,300,0 1408,328,1536,471,0 1354,458,1491,604,0 1484,435,1607,574,0 1616,347,1748,478,0 1705,436,1815,579,0 1615,479,1735,610,0 1456,565,1567,692,0 1581,611,1714,751,0 1712,569,1829,701,0 1454,701,1590,836,0 1417,817,1554,949,0 1576,757,1689,881,0 1687,733,1788,862,0 1769,843,1891,973,0 1540,873,1681,1002,0 1437,950,1577,1074,0 1642,951,1770,1077,0 1571,1005,1682,1127,0 1432,1075,1564,1204,0 1581,1123,1699,1259,0 1688,1082,1788,1212,0 1802,1030,1920,1157,0 1488,1207,1608,1333,0 1664,1189,1775,1330,0 1763,1159,1875,1298,0 1883,1137,1995,1258,0 1848,1234,1962,1353,0 1733,1260,1841,1372,0 1561,1272,1683,1407,0 1475,1368,1624,1497,0 1587,1429,1695,1557,0 1705,1394,1824,1518,0 1635,1523,1762,1654,0 1464,1482,1579,1609,0 1527,1603,1653,1714,0 1521,1710,1638,1831,0 1802,491,1909,619,0 1946,497,2059,627,0 2062,631,2179,756,0 1895,649,2011,767,0 1993,745,2117,876,0 1851,777,1968,894,0 1922,929,2035,1042,0 2012,881,2121,1008,0 1950,1019,2046,1122,0 2008,1084,2114,1200,0 1362,1222,1461,1304,0 1416,1250,1495,1331,0 1394,1332,1485,1414,0 1426,1381,1521,1444,0 1414,1497,1504,1559,0 1417,1557,1507,1625,0 1494,1531,1578,1601,0 1560,1513,1620,1572,0 1608,1458,1666,1526,0 1465,1464,1543,1540,0 1530,1444,1628,1529,0 1493,1355,1583,1433,0 1486,1259,1579,1337,0 1483,1189,1579,1266,0 1580,1286,1675,1375,0 1567,1340,1664,1427,0 1660,1329,1757,1410,0 1635,1399,1730,1487,0 1717,1398,1803,1477,0 1729,1307,1796,1383,0 1648,1225,1741,1311,0 1708,1234,1793,1325,0 1561,1134,1667,1201,0 1546,1077,1651,1158,0 1519,1012,1628,1103,0 1714,258,1826,369,0 1620,470,1726,571,0 1541,538,1655,647,0 1504,648,1612,757,0 1630,565,1717,664,0 1569,688,1665,779,0 1517,803,1623,895,0 1587,774,1676,866,0 1543,924,1654,1009,0 1593,965,1682,1032,0 1645,908,1744,1000,0 1640,987,1722,1061,0 1670,1074,1767,1170,0 1777,1162,1874,1237,0 1758,1077,1867,1163,0 1858,1130,1954,1211,0 1967,1116,2059,1206,0 1716,958,1822,1045,0 1854,1013,1947,1104,0 1866,950,1970,1028,0 1958,954,2043,1053,0 1795,886,1896,984,0 1733,822,1833,917,0 1891,864,1995,970,0 1822,779,1936,880,0 1960,866,2030,955,0 1949,758,2043,829,0 1947,696,2056,785,0 1670,696,1772,793,0 1765,716,1853,820,0 1816,655,1914,770,0 1890,652,1965,744,0 2008,626,2122,736,0 1715,512,1825,627,0 1901,534,2013,642,0 1778,423,1892,531,0`
**It's my train.txt**
**Many thanks in advance**

**Comment by asetkn** [comment]
Hi
Have you fixed this issue? If so how?
