### ISSUE TITLE
How to load the self-trained model to display the feature maps?

### ISSUE THREAD

**Issue by Bin-913** [qqwweee/keras-yolo3#480]
when I use the "load_model()", I get the following error:

```
from keras.models import load_model,Model
base_model = load_model('yolo_model.h5') #yolo_model.h5 is the model trained on my own 
                                                                       #dataset.
print(base_model.summary())
```

....
  File "C:\Users\ww\Desktop\PycharmProjects\YOLO\keras-yolo3\yolo3\model.py", line 459, in yolo_loss
    grid, raw_pred, pred_xy, pred_wh = yolo_head(yolo_outputs[l],
NameError: name 'yolo_head' is not defined

**Comment by bruzat** [comment]
Use :
base_model = YOLO(**{'model_path':'trained_weights_final.h5', 'classes':'N', 'classes_path':'xxxx'})

**Comment by Sylvia1018** [comment]
HI @Bin-913  sorry to disturb, but have u solved the issue? I happen to meet the same issue now. :)

**Comment by Bin-913** [comment]
> HI @Bin-913 sorry to disturb, but have u solved the issue? I happen to meet the same issue now. :)
I don't know the specific reason, but I can load the model in the file "yolo.py",  so I get the feature maps by modifying yolo.py.

**Comment by Bin-913** [comment]
@
I don't know the specific reason, but I can load the model in the file "yolo.py", so I get the feature maps by modifying yolo.py.

**Comment by Bin-913** [comment]
@Sylvia1018 
I don't know the specific reason, but the "load_model" in "yolo.py" can work. So I  get the feature maps by modifying the "yolo.py".

**Comment by Sylvia1018** [comment]
@Bin-913 Thanks for ur reply! Do you mean the following change?
        try:
            self.yolo_model = load_model(model_path, compile=False)
        except:
            self.yolo_model = tiny_yolo_body(Input(shape=(None,None,3)), num_anchors//2, num_classes) \
                if is_tiny_version else yolo_body(Input(shape=(None,None,3)), num_anchors//3, num_classes)
            self.yolo_model.load_model(self.model_path) # make sure model, anchors and classes match

Thanks!

**Comment by Bin-913** [comment]
@Sylvia1018 You can have a try.
For me, I return yolo_model from "generate(self)" and directly get the model from the class YOLO()

**Comment by Sylvia1018** [comment]
@Bin-913  
抱歉我没太看懂哎！ 可以麻烦您发一下训练和yolo.py的代码我研究一下下嘛！ 谢谢啦！

**Comment by Bin-913** [comment]
@Sylvia1018 给我邮箱地址

**Comment by Sylvia1018** [comment]
@Bin-913 
258399497@qq.com
太谢谢你啦！

**Comment by zhangyufei1995** [comment]
@Bin-913  2424661975@qq.com  感谢

**Comment by liyang0822** [comment]
@Bin-913 290957829@qq.com感谢

**Comment by 99103248** [comment]
@Bin-913  请问可以给我发一份么，我也是遇到了同样的错误。h5模型文件转pb的时候。NameError: name 'yolo_head' is not defined
邮箱：q99103248@gmail.com

**Comment by Byronnar** [comment]
@Bin-913 您好,请问可以给我发一份h5模型文件转pb的脚本么，我也是遇到了同样的错误。NameError: name 'yolo_head' is not defined
不胜感激
邮箱:601033628@qq.com

**Comment by Byronnar** [comment]
@Bin-913 您好，请问可以给我也发一份5模型文件转pb的脚本么，或者 训练和yolo.py的代码，我也是遇到了同样的错，NameError: name 'yolo_head' is not defined
邮箱：601033628@qq.com
谢谢

**Comment by bujianyiwang** [comment]
@Bin-913 你好,我也碰到一样的问题，麻烦发下h5转pb的脚本或训练和yolo.py的代码
2542876391@qq.com

**Comment by Qingfeng0623** [comment]
@Bin-913 Can you offer your modified code?My email is ye304810501@qq.com.Thanks!

**Comment by ShihuaiXu** [comment]
@Bin-913 531232693@qq.com 感谢

**Comment by nengbunengzhengdianqi** [comment]
> @Bin-913 [531232693@qq.com](mailto:531232693@qq.com) 感谢



> @Sylvia1018 给我邮箱地址

老哥，请问您解决了这个问题吗
