### ISSUE TITLE
Training Error: ValueError: invalid literal for int() with base 10: '' 

### ISSUE THREAD

**Issue by BenBenee** [qqwweee/keras-yolo3#489]
I'm trying to add my own dataset and train it with coco dataset also. I'm getting this error ValueError: invalid literal for int() with base 10: '' for this line of code  box = np.array([np.array(list(map(int,box.split(',')))) for box in line[1:]]) in utils.py

i've checked my annotation and all the format are correct. 
This is my annotation examples:
/mypath/train/111111000242.jpg 119,138,637,495,3 22,264,132,416,3
/mypath/train/111111000243.jpg 114,92,275,363,3 318,96,491,363,3 124,257,377,422,0 417,223,640,420,0
and so on

can anyone help me?

**Comment by asetkn** [comment]
Hi
Have you fixed this issue? If so how?

**Comment by BenBenee** [comment]
Hi
Yes I solved it,
I found out a mistake in my annotation. So if you have the same problem,
you should check your annotation carefully.

**Comment by IrisDinge** [comment]
> Hi Yes I solved it, I found out a mistake in my annotation. So if you have the same problem, you should check your annotation carefully.
> […](#)

Hi, I got same problem. could you pls give me some idea for checking my annotation? Because I have stared at those annotation file for a long while..... didn't find some point, thk in ad

**Comment by IrisDinge** [comment]
I fixed this, according to my dataset, lots of float;
if u got same problem, check the utils.py file and change the def get_random_data,
then change int to float. it may work!

Good Luck guys!

**Comment by BenBenee** [comment]
Make sure your annotation is in correct format.

Row format: image_file_path box1 box2 ... boxN;
Box format: x_min,y_min,x_max,y_max,class_id

I know it might be hard to find a mistake in long annotation. Or you can
make a program to check you annotation format.

In my case, i found a mistake in one of my box format that contain more
that 5 paramaters (i accidentally forgot to put a space between box format)
