### ISSUE TITLE
Detection Difference Between Darknet Model and Keras Model

### ISSUE THREAD

**Issue by nseidl** [qqwweee/keras-yolo3#491]
Has anyone experienced the same issue?

The model conversion process went smoothly but I wanted to test both just to make sure the same boxes appear but there is a difference.

Ideas I have that may cause a difference:
- Strange anchor conversion
- Image preprocessing differences
  - resizing method
  - RGB / BGR?

keras yolov3:
<img width="632" alt="keras" src="https://user-images.githubusercontent.com/22090294/59531340-b6486a00-8eb3-11e9-80ac-79702eb20969.png">

darknet: (no nms or anything; all raw boxes >= 0.25 are shown)
![darknet](https://user-images.githubusercontent.com/22090294/59531339-b6486a00-8eb3-11e9-82d4-c9c411bf1f54.png)

**Comment by thomasdf** [comment]
I have the same problem. Where darknet is able to find 5 boxes, this system is only able to find 3 of them. All boxes are of high confidence (>90%). Has anyone been able to find a solution for this?

**Comment by nseidl** [comment]
> 
> 
> I have the same problem. Where darknet is able to find 5 boxes, this system is only able to find 3 of them. All boxes are of high confidence (>90%). Has anyone been able to find a solution for this?

In my case, the significant difference was due to preprocessing input with letterboxing (maintaining aspect ratio while padding extra space with gray) in one case, and preprocessing input without letterboxing ('stretching' to network dimensions) in the other.
