### ISSUE TITLE
如果检测结果出现两类重叠怎么解决

### ISSUE THREAD

**Issue by HaiLongEmb** [qqwweee/keras-yolo3#496]
![123](https://user-images.githubusercontent.com/32731062/60144226-2c25cd00-97f4-11e9-8734-5e64d7996f09.jpg)

这种情况如何解决，请各位高手指教。

**Comment by HaiLongEmb** [comment]
上图中将一个目标同时认为成两个类，各位高手有除置信度阀值判断以外的方法吗？

**Comment by MelonWang9527** [comment]
@HaiLongEmb 
針對一張照片中所有 bounding box 做 NMS
如果兩個目標之間的 IoU 超過一定值，只留下置信度較高的那個

**Comment by boreas-l** [comment]
> @HaiLongEmb
> 針對一張照片中所有 bounding box 做 NMS
> 如果兩個目標之間的 IoU 超過一定值，只留下置信度較高的那個

那这样的话，如果两个物体之间靠的很近，会不会就容易出现漏检了吖？

**Comment by MelonWang9527** [comment]
@Phoenix-LXC 
會，所以看你的需求來決定要不要做這個動作

**Comment by boreas-l** [comment]
> @Phoenix-LXC
> 會，所以看你的需求來決定要不要做這個動作

可能是我自己太菜的原因，这个算法训练后的检测识别效果很不好。除了出现重叠检测以外，还会有漏检、错检这些情况。我是用VOC数据集。请问方便指点一下吗？谢谢。
