### ISSUE TITLE
Maximum of 20 objects

### ISSUE THREAD

**Issue by henry-eigen** [qqwweee/keras-yolo3#500]
The network will identify a maximum of 20 instances of a given object in an image. Example below

![download](https://user-images.githubusercontent.com/14300252/60401613-23196080-9b52-11e9-9593-be5088114d0f.png)

**Comment by Master-cai** [comment]
I met the same problem too. How to fix it?

**Comment by Master-cai** [comment]
I got it.Change the parameter "max_boxes" of the fun"yolo_eval" in "yolo3/models"which is 20 defaulted.
