### ISSUE TITLE
problem when execute convert.py

### ISSUE THREAD

**Issue by luhavis** [qqwweee/keras-yolo3#507]
i add 2 classes and change num classes(80->82)

python convert.py -w yolov3.cfg yolov3.weights model_data/yolo_weights.h5

buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array

but change classes(82-80), no problem

what i have missed?

**Comment by ravi02512** [comment]
As far as i concerned this repo is only  for coco dataset you can't convert you own model trained on darknet to keras model using this repo.
