### ISSUE TITLE
Does it perform data augmentation by default? Is it possible to do real time data augmentation, such as rotation , zoom (1-10%) horizontal and vertical flipping. ) 

### ISSUE THREAD

**Issue by yuki4ghub15** [qqwweee/keras-yolo3#509]
Hello 
Does Keras-Yolo3 perform data augmentation by default? 
Is it possible to do real time data augmentation, such as rotation , zoom (1-10%) horizontal and vertical flipping).

**Comment by cnmckee** [comment]
If you look at yolo3/utils.py you can see that in the function get_random_data(), which is called when the model is trained, data augmentation is performed.

**Comment by yuki4ghub15** [comment]
Thanks dude@cnmckee , I already got it.
