### ISSUE TITLE
[preprocess_true_boxes]IndexError: index 15 is out of bounds for axis 4 with size 15 

### ISSUE THREAD

**Issue by RoseChen** [qqwweee/keras-yolo3#51]
When I trained my own data,ran train.py,this error occurred in preprocess_true_boxes.
My true_boxes shape of (33402, 20, 5) and input_shape is (416,416)
`
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    main()
  File "train.py", line 151, in main
    y_true = preprocess_true_boxes(box_data, input_shape, anchors, len(class_names))
  File "/home/sk39/workspace/cheng/keras-yolo3-master/yolo3/model.py", line 266, in preprocess_true_boxes
    y_true[l][b, j, i, n, 5+c] = 1
IndexError: index 15 is out of bounds for axis 4 with size 15
`

Could you tell me how to solve it? 
Thank you!

**Comment by yinggo** [comment]
Have u solve this problem? I also meet similar problem,,,

**Comment by wizholy** [comment]
Have u solve this problem? I also meet similar problem,,,

**Comment by zuoxiang95** [comment]
i get the same error when i set ramdom=False in  https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/train.py#L175
