### ISSUE TITLE
"IndexError:only integers,slices,ellisis,numpy.newaxis and integer or boolean array are valid indices"

### ISSUE THREAD

**Issue by boreas-l** [qqwweee/keras-yolo3#525]
我检查过代码，也查过网上的一些信息，不过还是不太理解问题所在，有哪位大神指导一下？谢谢！
![QQ截图20190805223601](https://user-images.githubusercontent.com/41299014/62508605-da348600-b83a-11e9-8ec8-75ba370ae703.png)
`for t, n in enumerate(best_anchor):
       for l in range(num_layers):
             if n in anchor_mask[l]:
                   ............
                   y_true[l][b,j,i,k, 0:4] = true_boxes[b,t, 0:4]
                   y_true[l][b,j,i,k, 4] = 1
                   y_true[l][b,j,i,k, 5+c] = 1`

**Comment by SunYa0** [comment]
你好，我也遇到了这个错误，请问你解决了吗？
