### ISSUE TITLE
Mobilenetv2 and Efficientnet on yolov3

### ISSUE THREAD

**Issue by fsx950223** [qqwweee/keras-yolo3#528]
https://github.com/fsx950223/mobilenetv2-yolov3

**Comment by IrisDinge** [comment]
> https://github.com/fsx950223/mobilenetv2-yolov3

Hey, great work! I found you code before I got here.

some suggestions:
could u pls to offer more details just like qqwweee:
1. emphasize which version you use in keras, tensorflow even python. 
2. how to test your code with single image
...

Good work and have a nice day~
