### ISSUE TITLE
Skipping loading of weights for layers about training

### ISSUE THREAD

**Issue by Amerry-c** [qqwweee/keras-yolo3#53]
@qqwweee @tanakataiki hi,when i use 'python train.py' with my datasets(2 classes),i get the following information,cause the number of class different,some weights of convolutional layers did not load successfully，this can be trained and generate models,but the final test results deteriorated.how should I solve this problem？thank you so much.
/home/sugon/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((1, 1, 1024, 21) vs (255, 1024, 1, 1)).
  weight_values[i].shape))
/home/sugon/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((21,) vs (255,)).
  weight_values[i].shape))
/home/sugon/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((1, 1, 512, 21) vs (255, 512, 1, 1)).
  weight_values[i].shape))
/home/sugon/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((21,) vs (255,)).
  weight_values[i].shape))
/home/sugon/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((1, 1, 256, 21) vs (255, 256, 1, 1)).
  weight_values[i].shape))
/home/sugon/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((21,) vs (255,)).
  weight_values[i].shape))

**Comment by tanakataiki** [comment]
#34 is going to help you.
The warning wouldn't matter .

**Comment by Amerry-c** [comment]
@tanakataiki thanks for your help.
