### ISSUE TITLE
Invalid argument: Subshape must have...

### ISSUE THREAD

**Issue by skier233** [qqwweee/keras-yolo3#530]
I'm getting an error and not sure why:
Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)

**Comment by forsakenj** [comment]
hallo,have you solved it yet?

**Comment by shkkim** [comment]
have you solved it?

**Comment by shkkim** [comment]
> hallo,have you solved it yet?

Wondering have you solved it?

**Comment by skier233** [comment]
It was just a warning message and not the true message related to the error.

**Comment by forsakenj** [comment]
> > hallo,have you solved it yet?
> 
> Wondering have you solved it?
yes,I met the warning when I use gpu or large batch size, try to use cpu or small batch size
it just a warning and don't influence the result

**Comment by forsakenj** [comment]
> > hallo,have you solved it yet?
> 
> Wondering have you solved it?
> yes,I met the warning when I use gpu or large batch size, try to use cpu or small batch size
> it just a warning and don't influence the result

yes,I met the warning when I use gpu or large batch size, try to use cpu or small batch size
it just a warning and don't influence the result

**Comment by forsakenj** [comment]
> > hallo,have you solved it yet?
> 
> Wondering have you solved it?

yes,I met the warning when I use gpu or large batch size, try to use cpu or small batch size
it just a warning and don't influence the result

**Comment by shkkim** [comment]
> > > hallo,have you solved it yet?
> > 
> > 
> > Wondering have you solved it?
> 
> yes,I met the warning when I use gpu or large batch size, try to use cpu or small batch size
> it just a warning and don't influence the result

Thank you for the amazing help guys!!

**Comment by krishnak** [comment]
The actual solution is given here
https://stackoverflow.com/questions/57558476/training-a-keras-model-yields-multiple-optimizer-errors

**Comment by amirsultan** [comment]
Thanks krishnak. It seems like a warning in my case.

**Comment by wilbur-caper** [comment]
> > > hallo,have you solved it yet?
> > 
> > 
> > Wondering have you solved it?
> 
> yes,I met the warning when I use gpu or large batch size, try to use cpu or small batch size
> it just a warning and don't influence the result

did influence the speed of training?
