### ISSUE TITLE
关于数据预处理问题

### ISSUE THREAD

**Issue by tangchen2** [qqwweee/keras-yolo3#534]
我看到作者的实现中，加入了Data Augmentation，其中有一项是对image进行颜色的变换（distort）在我自己的数据集中，不同的类别是和颜色相关的，比如红色汽车和蓝色汽车会被标注为不同的类别，我想请问在这种情况下，是否应该去掉预处理过程中的color distort？因为我认为可能会破坏网络学习不同类别的颜色信息，还望有高手指点，谢谢！

**Comment by CGump** [comment]
you can't argue with that. you have to

**Comment by tangchen2** [comment]
you mean i have to disable the distort module, right?

**Comment by CGump** [comment]
> 
> 
> you mean i have to disable the distort module, right?

那必须的，数据增强里的颜色抖动会弱化模型对颜色的区别，而且还是在图片进行归一化后再加的抖动，以你的标签来看的话肯定是需要去掉的

**Comment by tangchen2** [comment]
好的，十分感谢你解决了我的疑惑！
Close it
