### ISSUE TITLE
运行yolo.py没有报错直接结束

### ISSUE THREAD

**Issue by cendelian** [qqwweee/keras-yolo3#535]
运行python yolo.py没有任何错误，直接结束，请问这是为什么呢？
此外，在预测图片放在哪？结果又在哪？我是小白。。。。。

**Comment by jefersonf** [comment]
Modify this [file](https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo_video.py#L6) at line 16 adding `r_image.save("your_image_filename", "JPEG")`

在第16行添加修改此文件
