### ISSUE TITLE
检测没有框

### ISSUE THREAD

**Issue by cendelian** [qqwweee/keras-yolo3#536]
检测没有框是为什么呢

**Comment by xm0629** [comment]
检测没有框,怎么解决的啊

**Comment by cloudhuang** [comment]
检测没有框，实际上是识别失败了

**Comment by Master-cai** [comment]
可以尝试将检测模型的score调至0，输出所有检测结果

**Comment by sail75** [comment]
我也遇到了这个问题，我的数据的loss已经下降到0.8左右，但是测试的时候没有检测到任何东西。我调低了模型的SCORE，检测了模型的输入，以及关闭了random。但是只有在score = 0的时候才能检测出框，而且是密密麻麻的框。。。。分布在图片的不同位置。请问您解决这个问题了吗？

**Comment by cendelian** [comment]
没解决，把训练模式注释掉 ，改为测试模式也不可以

**Comment by cendelian** [comment]
> 可以尝试将检测模型的score调至0，输出所有检测结果

哪里是调score的，是哪个文件？

**Comment by cendelian** [comment]
> 检测没有框，实际上是识别失败了

按照流程来的，不懂为什么会识别失败，

**Comment by azsxza** [comment]
我也没框，loss都到0.01了

**Comment by cendelian** [comment]
我换了官网下载的yolov3权重文件，可以了。以前是CSDN下载的，，有坑。。。。

**Comment by cendelian** [comment]
> 检测没有框,怎么解决的啊

- [ ] 我换了官网下载的yolov3权重文件，可以了。以前是CSDN下载的，，有坑。。。。
