### ISSUE TITLE
Has anyone tried to use C++ to call a trained model (model.h5)?

### ISSUE THREAD

**Issue by zhoujinhai** [qqwweee/keras-yolo3#546]
I added in train.py a model.save(log_dir + 'model.h5') next to the model.save_weights statement. I use the method gived by [amai](https://github.com/amir-abdi/keras_to_tensorflow) to convert the model.h5 to model.pb file, but I get the error that yolo_head is not defined in yolo_loss.

**Comment by a793719595** [comment]
1.you should model.save_weights then use this weights
2.英文太难写了，你就把keras_to_tensorflow.py文件里的定义model 修改一下，先加载出一个空的keras model出来 然后在加载你保存的权重，这个东西我前几天做过了 转换的pd没有精度损失。

**Comment by zhoujinhai** [comment]
1、这个第一条的意思是不用保存模型，直接保存权重就行吗？
2、第二条修改model是怎么修改一下，给小白指条明路，哈哈哈？

**Comment by a793719595** [comment]
只保存权重。那个转换文件需要你加载一个带权重的model，你先用yolo_body定义结构然后再加载权重就行了------------------ 原始邮件 ------------------
发件人: "zhoujinhai"<notifications@github.com>
发送时间: 2019年9月4日(星期三) 中午11:13
收件人: "qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com>;
抄送: "dashenyue"<793719595@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qqwweee/keras-yolo3] Has anyone tried to use C++ to call atrained model (model.h5)? (#546)



1、这个第一条的意思是不用保存模型，直接保存权重就行吗？
 2、第&#x4E8C;条修改model是怎么修改一下，给小白指条明路，&#x54C8;&#x54C8;&#x54C8;？
 
&mdash;

**Comment by zhoujinhai** [comment]
是在这里先保存吗
![image](https://user-images.githubusercontent.com/20365125/64230577-cb1b2380-cf1f-11e9-8bc1-9175b1841594.png)

**Comment by a793719595** [comment]
不是啊这是创造model 本身的训练程序就写了保存权重了 你只需要在转换文件里先定义出model_body 然后再加载权重就行了 




------------------ 原始邮件 ------------------
发件人: "zhoujinhai"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 下午2:25
收件人: "qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com>;
抄送: "山大王悦"<793719595@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qqwweee/keras-yolo3] Has anyone tried to use C++ to call atrained model (model.h5)? (#546)




是在这里先保存吗

**Comment by zhoujinhai** [comment]
是的 我刚改过来了 现在生成好了pb文件， 准备测试一下，你尝试过用opencv去调用模型吗

**Comment by a793719595** [comment]
我只测好了pd,老哥你要有下一步进展的话多沟通把。


------------------ 原始邮件 ------------------
发件人: "zhoujinhai"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 下午3:02
收件人: "qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com>;
抄送: "山大王悦"<793719595@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qqwweee/keras-yolo3] Has anyone tried to use C++ to call atrained model (model.h5)? (#546)




是的 我刚改过来了 现在生成好了pb文件， 准备测试一下，你尝试过用opencv去调用模型吗

**Comment by zhoujinhai** [comment]
测试你是用的yolo.py里头的detect_image不， 我测试完准备再看看能不能直接用opencv调。有进展的话一起讨论讨论 嘿嘿

**Comment by a793719595** [comment]
我觉得不能直接用吧 我是加载pb模型然后跑出 三个输出的卷积层 用yolo_eval得到过滤之后的框图数据在画图就行了






------------------ 原始邮件 ------------------
发件人: "zhoujinhai"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 下午3:06
收件人: "qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com>;
抄送: "山大王悦"<793719595@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qqwweee/keras-yolo3] Has anyone tried to use C++ to call atrained model (model.h5)? (#546)




测试你是用的yolo.py里头的detect_image不， 我测试完准备再看看能不能直接用opencv调。有进展的话一起讨论讨论 嘿嘿

**Comment by zhoujinhai** [comment]
我也不确定这个模型行不行，但opencv是有这种[例子](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API)的。那个测试脚本方便发我一份不，我先测试一下pb文件。

**Comment by a793719595** [comment]
用opencv跑就可以移植到c++了吗


------------------ 原始邮件 ------------------
发件人: "zhoujinhai"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 下午3:25
收件人: "qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com>;
抄送: "山大王悦"<793719595@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qqwweee/keras-yolo3] Has anyone tried to use C++ to call atrained model (model.h5)? (#546)




我也不确定这个模型行不行，但opencv是有这种例子的。那个测试脚本方便发我一份不，我先测试一下pb文件。

**Comment by zhoujinhai** [comment]
是这么想的 行不行得通就不知道了 先测下pb 哈哈哈

**Comment by zhoujinhai** [comment]
老哥 你测试脚本怎么写的 我这一直报错， 可以参考下你的脚本不

**Comment by a793719595** [comment]
我昨天不是发你一个吗 可能收不到文件吧 你直接用邮箱给我发个邮件




------------------ 原始邮件 ------------------
发件人: "zhoujinhai"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 晚上8:07
收件人: "qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com>;
抄送: "山大王悦"<793719595@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qqwweee/keras-yolo3] Has anyone tried to use C++ to call atrained model (model.h5)? (#546)




老哥 你测试脚本怎么写的 我这一直报错， 可以参考下你的脚本不

**Comment by zhoujinhai** [comment]
哥们 你的邮箱是这个吗 793719595@qq.com
我的是932853432@qq.com

**Comment by lukaisheng1203** [comment]
@a793719595 请问怎么使用pb模型进行测试啊

**Comment by wangwangww** [comment]
> 老哥 你测试脚本怎么写的 我这一直报错， 可以参考下你的脚本不

大佬，yolov3从h5转pb,我定义了model_body但最后报 'NoneType' object has no attribute 'outputs'，可不可以包你转换脚步发一份，最后你用opencv调用成功了吗，我最后也想在opencv中调用，求大佬们带带小白

**Comment by wangwangww** [comment]
> 我昨天不是发你一个吗 可能收不到文件吧 你直接用邮箱给我发个邮件
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "zhoujinhai"<notifications@github.com>; 发送时间: 2019年9月4日(星期三) 晚上8:07 收件人: "qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com>; 抄送: "山大王悦"<793719595@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [qqwweee/keras-yolo3] Has anyone tried to use C++ to call atrained model (model.h5)? (#546) 老哥 你测试脚本怎么写的 我这一直报错， 可以参考下你的脚本不 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

大佬可以将转换脚本和测试脚步发一份吗，按照你说的试了一下没成功，不知道哪里处理问题。非常感谢。

**Comment by zhoujinhai** [comment]
> > 老哥 你测试脚本怎么写的 我这一直报错， 可以参考下你的脚本不
> 
> 大佬，yolov3从h5转pb,我定义了model_body但最后报 'NoneType' object has no attribute 'outputs'，可不可以包你转换脚步发一份，最后你用opencv调用成功了吗，我最后也想在opencv中调用，求大佬们带带小白

```python
    model_body = yolo_body(image_input, num_anchors//3, num_classes)
    model_body.load_weights(weights_path, by_name=True, skip_mismatch=True)
    
    print("***********************************")
    print("input name is: ", model_body.input.name)
    for model_out in model_body.output:
        print("output name is: ", model_out.name)
```
在create_model函数中加这个，weights_path为你自己训练好的h5权重，然后保存为h5模型，再用  amai 的工程转就行了
