### ISSUE TITLE
Why did my 'val_loss' appear nan, is it that I modified the 'cfg' file?

### ISSUE THREAD

**Issue by YoooDT** [qqwweee/keras-yolo3#547]
And I also encountered the following error:

shape_optimizer failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)

**Comment by shkkim** [comment]
did you figure it out?

**Comment by YoooDT** [comment]
> did you figure it out?

i change the freeze mode 2 to 1 , the program become normal,    i  think it can help you

**Comment by shkkim** [comment]
hey thanks for the reply. I'm trying to train the model with my own data. If that's the case is freezing necessary?

**Comment by williamgun007** [comment]
@bigXpig where is the freeze mode ?

**Comment by williamgun007** [comment]
> > did you figure it out?
> 
> i change the freeze mode 2 to 1 , the program become normal, i think it can help you

i already change that mode to 1 in `train.py`, but the result still the same
