### ISSUE TITLE
shape_optimizer failed:  

### ISSUE THREAD

**Issue by YoooDT** [qqwweee/keras-yolo3#548]
shape_optimizer failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
 remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)

**Comment by shkkim** [comment]
Having the same issue....

**Comment by dmytro-kushnir** [comment]
the same story

**Comment by nyaang** [comment]
the sample problem, too. Did you solve the problem?

**Comment by Bjohnson131** [comment]
Also Having the same issue. Running on a Jetson Xavier.

**Comment by Bjohnson131** [comment]
so it comes from line 65 in train.py "callbacks=[logging, checkpoint])"

**Comment by Bjohnson131** [comment]
FIX:

In train.py change line

`is_tiny_version = len(anchors)==6 `

To

`is_tiny_version = False`

**Comment by krishnak** [comment]
The actual solution is given here
https://stackoverflow.com/questions/57558476/training-a-keras-model-yields-multiple-optimizer-errors
