### ISSUE TITLE
(again). error occur when convert yolov3.weighs to .h5 format

### ISSUE THREAD

**Issue by chobit19968535** [qqwweee/keras-yolo3#551]
I train the yolov3 model based on darknet with my own dataset. When i convert my yolo.weights to .h5 format, the error is followed:

Parsing section convolutional_73
conv2d bn leaky (3, 3, 128, 256)
Traceback (most recent call last):
  File "convert.py", line 264, in <module>
    _main(parser.parse_args())
  File "convert.py", line 145, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array

I have succeeded to convert and training other dataset, but in this case: 
I have 105 classes and filters = 330, when I convert .cfg and .weights to .h5, it will error.

I also notice that when the value of  " filters=(classes + 5 )*3 " bigger than 255 will raise same TypeError.

How should i do to solve my problem?
Thanks and Regards.

**Comment by chuasonglin** [comment]
@chobit19968535 Hi, I am facing the same problem as you, having many classes. How did you manage to solve it? Thanks in advance.
