### ISSUE TITLE
Error while using camera for detection

### ISSUE THREAD

**Issue by developomp** [qqwweee/keras-yolo3#554]
change `vid = cv2.VideoCapture(video_path)` to

```
try:
    int(video_path)
except ValueError:
    vid = cv2.VideoCapture(video_path)
else:
     vid = cv2.VideoCapture(int(video_path))
```
in yolo.py for camera usage.

**Comment by Borda** [comment]
it is fixed here - https://github.com/Borda/keras-yolo3/pull/9

**Comment by wowo68** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
