### ISSUE TITLE
convert to c++ with frugally-deep

### ISSUE THREAD

**Issue by aligoglos** [qqwweee/keras-yolo3#559]
I want to convert `yolo ` to c++ version with [frugally-deep
](https://github.com/Dobiasd/frugally-deep) so I need to convert model outputs to produce boxes and confidences and classes.
I know network has 3 outputs with shapes: `{[13 13 255] , [26 26 255], [52 52 255]}`.
I tried to re-code `yolo_eval ` method in `model.py` but I stuck in line : `input_shape = K.shape(yolo_outputs[0])[1:3] * 32` .
what is it? 
and why multiplication by 32 ?

**Comment by datduonguva** [comment]
Because 13x32=416, the input shape. In other words, the input size is
reduced by a factor of 32 after going through the darknet53.

**Comment by aligoglos** [comment]
thanks @datduonguva.
