### ISSUE TITLE
no code about yolo layer in model.py 

### ISSUE THREAD

**Issue by SanoPan0411** [qqwweee/keras-yolo3#57]
I read the source code carefully,but I found there is no thing mentioned about yolo layer.
I am new to yolov3,anyone can give a explanation of how yolo layer working?
Thank you all.

**Comment by qqwweee** [comment]
yolo3 output layers are conv layers, and the output of these conv layers must be translated into intuitive predictions. The translation is implemented by computation of tensors, in `yolo_eval`. And in `yolo.py` there `sess.run` runs the computation graph and get the predicitons.
So there is no yolo layer. and no need to use `model.predict`.
