### ISSUE TITLE
Have you run the scripts/kmeans.py by yourself? How about your  average iou result?

### ISSUE THREAD

**Issue by jwnirvana** [qqwweee/keras-yolo3#574]

**Comment by jwnirvana** [comment]
my result is so small
![Uploading 微信图片_20191030110010.jpg…]()

**Comment by jwnirvana** [comment]
my iou 
![微信图片_20191030110010](https://user-images.githubusercontent.com/40531215/67826690-596aea80-fb08-11e9-88d7-229d27aa2885.jpg)
result is so small

**Comment by tjmannn** [comment]
K anchors:
 [[ 32  39]
 [ 46  69]
 [ 49  50]
 [ 57  33]
 [ 70  64]
 [ 83  85]
 [108  49]
 [121 101]
 [225 252]]
Accuracy: 78.51%
