### ISSUE TITLE
Indentation bug?

### ISSUE THREAD

**Issue by DdHms** [qqwweee/keras-yolo3#603]
In the `yolo_loss` method there seems to be an indentation bug.
To my understanding lines: 395-411 should bu un-indented after all when if we finished updating the ignore mask the losses are calculated for all scales all together, as it is written now the losses overwrite themselves every scale

**Comment by tabmoo** [comment]
But the variable 'loss' doesn't overwrite itself and accumulates. Right?

Also, losses are calculated separately on each scale 'l'.

**Comment by DdHms** [comment]
> But the variable 'loss' doesn't overwrite itself and accumulates. Right?
> 
> Also, losses are calculated separately on each scale 'l'.

None of the losses: xy, wh, class, confidence have a `l` index so it seems they do overwrite themselves.

**Comment by tabmoo** [comment]
> > But the variable 'loss' doesn't overwrite itself and accumulates. Right?
> > Also, losses are calculated separately on each scale 'l'.
> 
> None of the losses: xy, wh, class, confidence have a `l` index so it seems they do overwrite themselves.

raw_true_xy depends on y_true[l][..., :2]
raw_true_wh depends on y_true[l][..., 2:4]
raw_pred depends on evaluation of yolo_head which is itself calculated on the scale 'l'.

And so on.

**Comment by DdHms** [comment]
Sorry my bad
