### ISSUE TITLE
How to use my   trained model？

### ISSUE THREAD

**Issue by gdyxml2000** [qqwweee/keras-yolo3#61]
I trained my own model my_yolo.h5 as required, but when I modify self.model_path = 'model_data/my_yolo.h5' in yolo.py and run it, the result prompts:
InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 12675 values, but the requested shape requires a multiple of 43095

so, how to use my trained model?

**Comment by qqwweee** [comment]
modify `classes_path = my_classes.txt`.

**Comment by gdyxml2000** [comment]
good,it`s done!  nice work!! thanks!!
