### ISSUE TITLE
How to replace session.run() with keras Model() for predictions?

### ISSUE THREAD

**Issue by look4pritam** [qqwweee/keras-yolo3#611]
How to replace session.run() with keras Model() for predictions?

**Comment by areebsyed** [comment]
just downgrade tensorflow==2.0 to tensorflow==1.14. Worked for me

**Comment by eatgrass** [comment]
self.sess = tf.compat.v1.keras.backend.get_session()

**Comment by look4pritam** [comment]
Got it. In this way almost all TensorFlow-1 functionality can be used.
