### ISSUE TITLE
A fileNotFoundError in train.py

### ISSUE THREAD

**Issue by flyhuiyi** [qqwweee/keras-yolo3#628]
FileNotFoundError: [Errno 2] No such file or directory: '0002'（我的图片名是0000.jpg-0007.jpg共8张）是找不到图片或者标签路径的问题吗？同时不修改代码重新运行的话，又会出现：FileNotFoundError: [Errno 2] No such file or directory: '0004'，其他的路径找不到，每次报错都不一样。

**Comment by flyhuiyi** [comment]
> ```
>    FileNotFoundError: [Errno 2] No such file or directory: '0002'（我的图片名是0000.jpg-0007.jpg共8张）是找不到图片或者标签路径的问题吗？同时不修改代码重新运行的话，又会出现：FileNotFoundError: [Errno 2] No such file or directory: '0004'，其他的路径找不到，每次报错都不一样。
> ```

**Comment by wyjko** [comment]
I have the same problem. Have you solved it? thank you!

**Comment by Kuuuo** [comment]
Have you solved the problem yet? I made a similar mistake
