### ISSUE TITLE
你可以尝试删除tensorflow版本留下tensorflow-gpu，那样他会强制性执行gpu或者你可以看一下你的cuda与cudnn，gpu驱动都是否安装正确

### ISSUE THREAD

**Issue by flyhuiyi** [qqwweee/keras-yolo3#639]
你可以尝试删除tensorflow版本留下tensorflow-gpu，那样他会强制性执行gpu或者你可以看一下你的cuda与cudnn，gpu驱动都是否安装正确

------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Master-cai"<notifications@github.com&gt;; 
发送时间: 2020年3月8日(星期天) 中午12:19
收件人: "qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com&gt;; 
抄送: "1342868324"<1342868324@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [qqwweee/keras-yolo3] yolo v3中文交流 (#254)

 
有个问题想问一下，yolo的基本功能我已实现，但是在调用本地摄像头进行实时的视频识别时，fps只有1，估计用gpu会好点。虽然我在python里安装了tensorflow-gpu,但识别时发现GPU的占有率只有1%-3%，需要什么步骤（CUDA之类）可以实现用gpu识别，求指点。
  
您好，想请教一下如何实现实时的视频检测？
 
— 
因为评论，您收到此消息。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

_Originally posted by @AadeIT in https://github.com/qqwweee/keras-yolo3/issues/254#issuecomment-597581377_

  感谢，已经解决，之前的tensorflow-gpu是使用pip直接install,无法匹配CUDA,后安装了专门编译后好tensorflow-gpu后成功调用gpu.

**Comment by flyhuiyi** [comment]
> 你可以尝试删除tensorflow版本留下tensorflow-gpu，那样他会强制性执行gpu或者你可以看一下你的cuda与cudnn，gpu驱动都是否安装正确
> 
> ------------------ 原始邮件 ------------------
> 发件人: "Master-cai"<[notifications@github.com](mailto:notifications@github.com)>;
> 发送时间: 2020年3月8日(星期天) 中午12:19
> 收件人: "qqwweee/keras-yolo3"<[keras-yolo3@noreply.github.com](mailto:keras-yolo3@noreply.github.com)>;
> 抄送: "1342868324"<[1342868324@qq.com](mailto:1342868324@qq.com)>; "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>;
> 主题: Re: [qqwweee/keras-yolo3] yolo v3中文交流 (#254)
> 
> 有个问题想问一下，yolo的基本功能我已实现，但是在调用本地摄像头进行实时的视频识别时，fps只有1，估计用gpu会好点。虽然我在python里安装了tensorflow-gpu,但识别时发现GPU的占有率只有1%-3%，需要什么步骤（CUDA之类）可以实现用gpu识别，求指点。
> 
> 您好，想请教一下如何实现实时的视频检测？
> 
> —
> 因为评论，您收到此消息。
> 直接回复此电子邮件，在GitHub上查看，或取消订阅。
> 
> _Originally posted by @AadeIT in [#254 (comment)](https://github.com/qqwweee/keras-yolo3/issues/254#issuecomment-597581377)_
> 
> 感谢，已经解决，之前的tensorflow-gpu是使用pip直接install,无法匹配CUDA,后安装了专门编译后好tensorflow-gpu后成功调用gpu.

**Comment by zimo054** [comment]
问下，tensorflow-gpu安装的是什么版本
