### ISSUE TITLE
how to measure the map?

### ISSUE THREAD

**Issue by wizholy** [qqwweee/keras-yolo3#65]
after model training, how to measure the map?

**Comment by guojiapeng00** [comment]
hello,wizholy,i konw that you have trained the yolo3, but i met a problem
i have a question that :how to modify the train.py,  (what to do with  the *,such as  [*model_body.output, *y_true]))

thanks

**Comment by galaktyk** [comment]
https://github.com/Cartucho/mAP

**Comment by Deepcong2019** [comment]
Maybe you can look look this https://github.com/Deepcong2019/yolov3.keras
