### ISSUE TITLE
How can I continue my last training?

### ISSUE THREAD

**Issue by LAWSSSS** [qqwweee/keras-yolo3#652]

**Comment by Breezewrf** [comment]
I have the same question, since the training time is too long

**Comment by hexin6688** [comment]
hi,do you sovle this problem?

**Comment by LAWSSSS** [comment]
@hexin6688 @Breezewrf  I figure out a way by myself. My connection to the remote server is unstable and always disconnects from time to time. So firstly, I make some changes to the following codes in `train.py`:
```
checkpoint = ModelCheckpoint(log_dir + 'ep{epoch:03d}-loss{loss:.3f}-val_loss{val_loss:.3f}.h5',
                                 monitor='val_loss', save_weights_only=True, save_best_only=True, period=2)
```
I changed the parameter "period" from 3 to 2 in order to save checkpoint file .h5 much more frequently.  Then I make a few changes to the following code in "train.py":
```
model = create_model(input_shape, anchors, num_classes,
                             freeze_body=2,
                             weights_path='model_data/ep045-loss16.671-val_loss15.866.h5')  # make sure you know what you freeze
```
Change the weights path to your latest checkpoint file, and then make some final changes to the code:
```
# Train with frozen layers first, to get a stable loss.
    # Adjust num epochs to your dataset. This step is enough to obtain a not bad model.
    if False:
        model.compile(optimizer=Adam(lr=1e-3), loss={
            # use custom yolo_loss Lambda layer.
            'yolo_loss': lambda y_true, y_pred: y_pred})

        batch_size = 32
        print('Train on {} samples, val on {} samples, with batch size {}.'.format(num_train, num_val, batch_size))
        model.fit_generator(data_generator_wrapper(lines[:num_train], batch_size, input_shape, anchors, num_classes),
                steps_per_epoch=max(1, num_train//batch_size),
                validation_data=data_generator_wrapper(lines[num_train:], batch_size, input_shape, anchors, num_classes),
                validation_steps=max(1, num_val//batch_size),
                epochs=50,
                initial_epoch=0,
                callbacks=[logging, checkpoint])
        model.save_weights(log_dir + 'trained_weights_stage_1.h5')

    # Unfreeze and continue training, to fine-tune.
    # Train longer if the result is not good.
    if True:
        for i in range(len(model.layers)):
            model.layers[i].trainable = True
        # model.compile(optimizer=Adam(lr=1e-4), loss={'yolo_loss': lambda y_true, y_pred: y_pred}) # recompile to apply the change
        model.compile(optimizer=Adam(lr=1e-3),
                      loss={'yolo_loss': lambda y_true, y_pred: y_pred})  # recompile to apply the change
        print('Unfreeze all of the layers.')

        # batch_size = 32 # note that more GPU memory is required after unfreezing the body
        batch_size = 20  # note that more GPU memory is required after unfreezing the body
        print('Train on {} samples, val on {} samples, with batch size {}.'.format(num_train, num_val, batch_size))
        model.fit_generator(data_generator_wrapper(lines[:num_train], batch_size, input_shape, anchors, num_classes),
            steps_per_epoch=max(1, num_train//batch_size),
            validation_data=data_generator_wrapper(lines[num_train:], batch_size, input_shape, anchors, num_classes),
            validation_steps=max(1, num_val//batch_size),
            epochs=50,
            initial_epoch=45,
            callbacks=[logging, checkpoint, reduce_lr, early_stopping])
        model.save_weights(log_dir + 'trained_weights_final.h5')
```
Set the first "True" to "False" and set the initial epoch in the second loop to your latest checkpoint file's epoch.

**Comment by hexin6688** [comment]
> 
> 
> @hexin6688 @Breezewrf I figure out a way by myself. My connection to the remote server is unstable and always disconnects from time to time. So firstly, I make some changes to the following codes in `train.py`:
> 
> ```
> checkpoint = ModelCheckpoint(log_dir + 'ep{epoch:03d}-loss{loss:.3f}-val_loss{val_loss:.3f}.h5',
>                                  monitor='val_loss', save_weights_only=True, save_best_only=True, period=2)
> ```
> 
> I changed the parameter "period" from 3 to 2 in order to save checkpoint file .h5 much more frequently. Then I make a few changes to the following code in "train.py":
> 
> ```
> model = create_model(input_shape, anchors, num_classes,
>                              freeze_body=2,
>                              weights_path='model_data/ep045-loss16.671-val_loss15.866.h5')  # make sure you know what you freeze
> ```
> 
> Change the weights path to your latest checkpoint file, and then make some final changes to the code:
> 
> ```
> # Train with frozen layers first, to get a stable loss.
>     # Adjust num epochs to your dataset. This step is enough to obtain a not bad model.
>     if False:
>         model.compile(optimizer=Adam(lr=1e-3), loss={
>             # use custom yolo_loss Lambda layer.
>             'yolo_loss': lambda y_true, y_pred: y_pred})
> 
>         batch_size = 32
>         print('Train on {} samples, val on {} samples, with batch size {}.'.format(num_train, num_val, batch_size))
>         model.fit_generator(data_generator_wrapper(lines[:num_train], batch_size, input_shape, anchors, num_classes),
>                 steps_per_epoch=max(1, num_train//batch_size),
>                 validation_data=data_generator_wrapper(lines[num_train:], batch_size, input_shape, anchors, num_classes),
>                 validation_steps=max(1, num_val//batch_size),
>                 epochs=50,
>                 initial_epoch=0,
>                 callbacks=[logging, checkpoint])
>         model.save_weights(log_dir + 'trained_weights_stage_1.h5')
> 
>     # Unfreeze and continue training, to fine-tune.
>     # Train longer if the result is not good.
>     if True:
>         for i in range(len(model.layers)):
>             model.layers[i].trainable = True
>         # model.compile(optimizer=Adam(lr=1e-4), loss={'yolo_loss': lambda y_true, y_pred: y_pred}) # recompile to apply the change
>         model.compile(optimizer=Adam(lr=1e-3),
>                       loss={'yolo_loss': lambda y_true, y_pred: y_pred})  # recompile to apply the change
>         print('Unfreeze all of the layers.')
> 
>         # batch_size = 32 # note that more GPU memory is required after unfreezing the body
>         batch_size = 20  # note that more GPU memory is required after unfreezing the body
>         print('Train on {} samples, val on {} samples, with batch size {}.'.format(num_train, num_val, batch_size))
>         model.fit_generator(data_generator_wrapper(lines[:num_train], batch_size, input_shape, anchors, num_classes),
>             steps_per_epoch=max(1, num_train//batch_size),
>             validation_data=data_generator_wrapper(lines[num_train:], batch_size, input_shape, anchors, num_classes),
>             validation_steps=max(1, num_val//batch_size),
>             epochs=50,
>             initial_epoch=45,
>             callbacks=[logging, checkpoint, reduce_lr, early_stopping])
>         model.save_weights(log_dir + 'trained_weights_final.h5')
> ```
> 
> Set the first "True" to "False" and set the initial epoch in the second loop to your latest checkpoint file's epoch.

你好，我完成了第一阶段的训练，然后进入到第二阶段的时候，显存不够了，我可以直接加载第一阶段的模型，注释第一阶段的代码，直接进入到stage_2阶段么？

**Comment by LAWSSSS** [comment]
@hexin6688 显存不够应该是个通病，我NVIDIA Tesla V100 16G也会不够，必须要把batch_size改小才行。当然可以注释掉第一阶段，第二阶段只要注意把读取的模型文件改成你最新训练的就行。
