### ISSUE TITLE
I tried to add support for Yolo3 Tiny but failed

### ISSUE THREAD

**Issue by netw0rkf10w** [qqwweee/keras-yolo3#66]
Hello,

Thanks a lot for the code!

It's a pity that it does not support Yolo3 Tiny yet, so I gave it a try.

In `convert.py`, add `MaxPooling2D` to [line 15](https://github.com/qqwweee/keras-yolo3/blob/3f93a896ba17a1b18ab665837ec7152a294a5095/convert.py#L15):

```
from keras.layers import (Conv2D, Input, ZeroPadding2D, Add,
                          UpSampling2D, Concatenate, MaxPooling2D)
```

Then add support for max-pooling at [line 17](https://github.com/qqwweee/keras-yolo3/blob/3f93a896ba17a1b18ab665837ec7152a294a5095/convert.py#L217):

```
    elif section.startswith('maxpool'):
            stride = int(cfg_parser[section]['stride'])
            size = int(cfg_parser[section]['size'])
            all_layers.append(MaxPooling2D(pool_size=(size, size), strides=(stride,stride))(prev_layer))
            prev_layer = all_layers[-1]    
```
Next, in `yolo3/model.py`, change [line 168](https://github.com/qqwweee/keras-yolo3/blob/3f93a896ba17a1b18ab665837ec7152a294a5095/yolo3/model.py#L168) from

`for l in range(3):`

to

`for l in range(len(yolo_outputs)):`

Results: the model was successfully converted, but then when testing with `yolo.py` I got the following error:

> InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1,24,24,128] vs. shape[1] = [1,26,26,256]
> 	 [[Node: concatenate_1/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](up_sampling2d_1/ResizeNearestNeighbor, leaky_re_lu_5/LeakyRelu/Maximum, mul_16/y)]]

Could you please help me to resolve this?
Thank you so much in advance!

**Comment by netw0rkf10w** [comment]
Problem solved:

`all_layers.append(MaxPooling2D(pool_size=(size, size), strides=(stride,stride), border_mode='same')(prev_layer))`

**Comment by fangmingbnu** [comment]
@netw0rkf10w Hi, I followed your way and convert successfully now. But I find that the one people sometimes has two boxs. one box is tall and thin. another box is low and wide. Do you noticed about this when you do detection? Thank you!

**Comment by netw0rkf10w** [comment]
@fangmingbnu Make sure you use the right set the anchors for tiny Yolo ;)

**Comment by fangmingbnu** [comment]
@netw0rkf10w  I am using the origin anchors values which is 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326. Could you please tell me which values set I should use? Thank you!

**Comment by netw0rkf10w** [comment]
@fangmingbnu Try the following:
> 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
Then if you use  you may need to modify `yolo3/model.py` accordingly.

But then, I think @qqwweee have just updated the code to support tiny Yolo, so all you need to do now is to download the latest version of the code ;)

**Comment by sushant1727** [comment]
Do we've to generate anchors file specific to our yolo model or one in the repo is generic ?
