### ISSUE TITLE
How to modify if I donnot load all the training data into memory

### ISSUE THREAD

**Issue by wanjinchang** [qqwweee/keras-yolo3#67]
dear author:
   I want to know if i donnot load the training data into memory instead of loading the training data by python generator?? Looking forward to your reply!!

**Comment by qqwweee** [comment]
`fit_generator` in Keras is helpful. I'm working on that.

**Comment by wanjinchang** [comment]
Thank you for your reply.I'm doing this, I modify the code of get_training_data to the follow:
`def generate_batch_data(data, anchors, class_names, max_boxes=100):
    while True:
        image_data = []
        box_data = []
        for line in data:
            line = line.split(' ')
            print("processing on:", line[0])
            filename = data_dir + line[0]
            image = Image.open(filename)
            # print(image)
            boxed_image = letterbox_image(image, tuple(reversed(input_shape)))
            image_data.append(np.array(boxed_image, dtype='uint8'))

            boxes = np.zeros((max_boxes, 5), dtype='int32')
            for i, box in enumerate(line[1:]):
                if i < max_boxes:
                    boxes[i] = np.array(list(map(int, box.split(','))))
                else:
                    break
            image_size = np.array(image.size)
            input_size = np.array(input_shape[::-1])
            new_size = (image_size * np.min(input_size / image_size)).astype('int32')
            boxes[:i + 1, 0:2] = (boxes[:i + 1, 0:2] * new_size / image_size + (input_size - new_size) / 2).astype(
                'int32')
            boxes[:i + 1, 2:4] = (boxes[:i + 1, 2:4] * new_size / image_size + (input_size - new_size) / 2).astype(
                'int32')
            box_data.append(boxes)
            print("len:", len(image_data))
            if len(image_data) == batch_size:
                image_data = np.array(image_data) / 255.
                box_data = np.array(box_data)
                y_true = preprocess_true_boxes(box_data, input_shape, anchors, len(class_names))
                print("image_data:", image_data.shape)
                # print("type:", type(image_data))     # <class 'numpy.ndarray'>
                print("y_true:", len(y_true))
                # print("y_type:", type(y_true))       # <class 'list'>
                yield (image_data, y_true)
                image_data = []
                box_data = []`
and use the 
`model.fit_generator(generate_batch_data(train_data, anchors, class_names),
                        steps_per_epoch=num_train // batch_size,
                        epochs=30,
                        verbose=1,
                        callbacks=callbacks,
                        validation_data=generate_batch_data(val_data, anchors, class_names),
                        validation_steps=num_val // batch_size)`
but get an error like this:
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 4 array(s), but instead got the following list of 1 arrays.
How to solve that?

**Comment by wanjinchang** [comment]
Thank you for your reply.I'm doing this, I modify the code of get_training_data to the follow:
`
def generate_batch_data(data, anchors, class_names, max_boxes=100):
while True:
image_data = []
box_data = []
for line in data:
line = line.split(' ')
print("processing on:", line[0])
filename = data_dir + line[0]
image = Image.open(filename)
# print(image)
boxed_image = letterbox_image(image, tuple(reversed(input_shape)))
image_data.append(np.array(boxed_image, dtype='uint8'))

        boxes = np.zeros((max_boxes, 5), dtype='int32')
        for i, box in enumerate(line[1:]):
            if i < max_boxes:
                boxes[i] = np.array(list(map(int, box.split(','))))
            else:
                break
        image_size = np.array(image.size)
        input_size = np.array(input_shape[::-1])
        new_size = (image_size * np.min(input_size / image_size)).astype('int32')
        boxes[:i + 1, 0:2] = (boxes[:i + 1, 0:2] * new_size / image_size + (input_size - new_size) / 2).astype(
            'int32')
        boxes[:i + 1, 2:4] = (boxes[:i + 1, 2:4] * new_size / image_size + (input_size - new_size) / 2).astype(
            'int32')
        box_data.append(boxes)
        print("len:", len(image_data))
        if len(image_data) == batch_size:
            image_data = np.array(image_data) / 255.
            box_data = np.array(box_data)
            y_true = preprocess_true_boxes(box_data, input_shape, anchors, len(class_names))
            print("image_data:", image_data.shape)
            # print("type:", type(image_data))     # <class 'numpy.ndarray'>
            print("y_true:", len(y_true))
            # print("y_type:", type(y_true))       # <class 'list'>
            yield (image_data, y_true)
            image_data = []
            box_data = []`
and use the
model.fit_generator(generate_batch_data(train_data, anchors, class_names), steps_per_epoch=num_train // batch_size, epochs=30, verbose=1, callbacks=callbacks, validation_data=generate_batch_data(val_data, anchors, class_names), validation_steps=num_val // batch_size)
but get an error like this:
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 4 array(s), but instead got the following list of 1 arrays.
How to solve that?
