### ISSUE TITLE
failed to start training when num classes is very small, e.g. 1

### ISSUE THREAD

**Issue by chrjxj** [qqwweee/keras-yolo3#69]
e.g. when num class = 1, 

preprocess_true_boxes run into error.

```y_true[l][b, j, i, n, 5+c] = 1``` will raise Index error, out of range; e.g.  C could 6, 5+c =11 , while the y_true[l] axis 4 is only 6 dim.

**Comment by ewen1024** [comment]
yeah you right, I just wanted to post this issue. For me,  classes 5    so  filter 30 and got the feedback 
IndexError: index 10 is out of bounds for axis 4 with size 10

And when you set the  classes 5  .  it's fine to work, so is that something related to   classes+5 so needs to be more than 5
![1screenshot from 2018-05-25 20-08-45](https://user-images.githubusercontent.com/33156660/40543565-974dfec0-6057-11e8-8eaa-d600df6880f5.png)

**Comment by qqwweee** [comment]
I think you tried different datasets but didn't produce new .npz file.
Try `load_previous=False` in `get_training_data`.

**Comment by ewen1024** [comment]
@qqwweee   I am using new dataset with 5 classes.  I  produced the npz file  and set load_previous =False
and goes  IndexError: index 10 is out of bounds for axis 4 with size 10
  like before

classes =5

**Comment by qqwweee** [comment]
The class ids in your annotation file should be 0 to 4. Is there a 5?

**Comment by ewen1024** [comment]
@qqwweee  thank you!
