### ISSUE TITLE
I want to see the feature amount.

### ISSUE THREAD

**Issue by kotamumu** [qqwweee/keras-yolo3#693]
I want to do feature visualization in YOLOv3.
I'd like to know where YOLOv3 is looking and judging.
Can you please tell me?

**Comment by dongzhongxian** [comment]
I    found it    on github   .  You can  search the Keyword by YOLOv3，If
you want to find   go or  python   programming languages , you can choose
your own

**Comment by kotamumu** [comment]
I was able to find a feature visualization about YOLOv3 on github.
I found this "feature-vis-yolov3".
I don't know how to use it yet, but I'm glad to see that it's helping to clear the way for some solutions.
Thank you.
