### ISSUE TITLE
What happens to the input image?

### ISSUE THREAD

**Issue by Kot-Nak8** [qqwweee/keras-yolo3#707]
How is the image input to the detector processed?
I'm not sure if this is correct, but the image I checked had these additional gray areas at the top and bottom.
Will there be another process after this to add gray areas on the left and right?
I hope someone can tell me about it.
![im2](https://user-images.githubusercontent.com/66671473/87241782-6135a980-c461-11ea-8e0d-2846fdece0df.png)

**Comment by Kot-Nak8** [comment]
Depending on the weights used, this can cause false positives at both ends of the screen. I would like to know how the processing of the input image affects both ends of the screen.

**Comment by tfukumori** [comment]
In conclusion, if the image is already resized to 416 x 416 like the one shown, I don't think it will be filled with even more gray.

The image size required by the YOLO 416 is 416 x 416 pixels.
To make the input 416 x 416, filled it in with gray in the following code.

https://github.com/qqwweee/keras-yolo3/blob/master/yolo3/utils.py

def letterbox_image(image, size)` in /master/yolo3/utils.py

Translated with www.DeepL.com/Translator (free version)

**Comment by Kot-Nak8** [comment]
Thanks to you, I see that there is no additional processing on either side.
Thanks so much!
