### ISSUE TITLE
I want to display the grid cell.

### ISSUE THREAD

**Issue by Kot-Nak8** [qqwweee/keras-yolo3#709]
I found this image from a search, but I want to display the detection results in a grid cell like this one.
Can someone please tell me how to do this?
<img width="769" alt="スクリーンショット 2020-07-18 17 50 32" src="https://user-images.githubusercontent.com/66671473/87848933-ae14f680-c91f-11ea-8f4a-3dd9f7e1c69b.png">

**Comment by FlavioValcarce** [comment]
Don't know
