### ISSUE TITLE
why the speed of videos only 1 fps

### ISSUE THREAD

**Issue by ll1214** [qqwweee/keras-yolo3#72]
it so slow!

**Comment by qqwweee** [comment]
Use your GPU.

**Comment by ll1214** [comment]
thank you very much

**Comment by ll1214** [comment]
But how to set GPU to run it ,because my environment is tensorflow-gpu and it can noly use GPU

**Comment by ll1214** [comment]
And I haved just uninstall the Theano，but it didn't work

**Comment by qqwweee** [comment]
Did you install CUDA and cuDNN?

**Comment by ll1214** [comment]
Yes I have installed

**Comment by ll1214** [comment]
And My computer graphics card is GTX960M

**Comment by qqwweee** [comment]
The device information is displayed on the screen when you run tensorflow. Read it and find what happened.

**Comment by ll1214** [comment]
I shows thUsing TensorFlow backend.
model_data/yolo.h5 model, anchors, and classes loaded.
(416, 416, 3)
Found 9 boxes for img
truck 0.36 (361, 122) (458, 203)
truck 0.48 (368, 95) (498, 186)
car 0.32 (201, 125) (356, 191)
car 0.51 (244, 128) (406, 205)
car 0.53 (361, 122) (458, 203)
car 0.96 (694, 152) (745, 189)
car 0.98 (624, 153) (697, 204)
car 0.99 (183, 149) (336, 287)
person 0.33 (529, 145) (543, 175)
2.37719493887547
(416, 416, 3)
Found 6 boxes for img
truck 0.57 (335, 90) (479, 181)
car 0.86 (309, 127) (420, 208)
car 0.88 (197, 117) (317, 222)
car 0.95 (623, 152) (696, 201)
car 0.96 (703, 150) (755, 187)
person 0.43 (533, 147) (548, 173)
1.6571010365649785
(416, 416, 3)at :

**Comment by ll1214** [comment]
Another idea is whether I can train a model to identify traffic signs and objects at the same time.

**Comment by ll1214** [comment]
The traffic sign data set is in http://cg.cs.tsinghua.edu.cn/traffic-sign/, which is a data set rented by Tsinghua University.

**Comment by ll1214** [comment]
The useful information I got from above is that the prediction time for each frame is 1.7s.

**Comment by qqwweee** [comment]
Did GPU work before? Perhaps the environment is not correctly configured. Search the internet for solution.

Traffic sign is more like Vehicle License Plate Recognition and is unsuited to Object Detection, I think.

**Comment by ll1214** [comment]
Yes I thank you are right ,I just uninstalled tensorflow-gpu and install tensorflow.The speed is same.And I run it in windows

**Comment by ll1214** [comment]
But my idea is to make yolov3 identify traffic signs on general testing, but it only adds a few more categories.

**Comment by qqwweee** [comment]
Then it is feasible someway. Just make a try.

**Comment by TommyAnqi** [comment]
Most of the time consumed on image preprocessing.  Only print the time on the forward part

**Comment by ll1214** [comment]
Thanks for your help,and maybe we could make friends.I have recently studied the analysis and prediction of medical imaging. Lung cancer prediction in kaggle games
