### ISSUE TITLE
modify train.py

### ISSUE THREAD

**Issue by guojiapeng00** [qqwweee/keras-yolo3#73]
there is a lot of     *     in train.py

for example  :      model_loss = Lambda(yolo_loss, output_shape=(1,), name='yolo_loss',
        arguments={'anchors': anchors, 'num_classes': num_classes, 'ignore_thresh': 0.5})(
        [*model_body.output, *y_true])

could any body  tell me what i should do to them?

**Comment by qqwweee** [comment]
There is no need to change them.
*expression is to expand the list, e.g. `[a, b, c]` -> `a, b, c`.

**Comment by jacobunderlinebenseal** [comment]
i got a 'SyntaxError: invalid syntax' for that, i am python2.7
