### ISSUE TITLE
Train Single Label Detection

### ISSUE THREAD

**Issue by malik-anhar** [qqwweee/keras-yolo3#749]
Let's say I wanna train the model only for single label (face), so what is the correct annotation for the train.txt? 
Is it something like this
```
path/to/img1.jpg 50,100,150,200,0 30,50,200,120,0
path/to/img2.jpg 120,300,250,600,0
```
or something like this
```
path/to/img1.jpg 50,100,150,200,1 30,50,200,120,1
path/to/img2.jpg 120,300,250,600,1
```
The class_id should be 0 or 1?

**Comment by Anyman552** [comment]
The class_id should be 0
