### ISSUE TITLE
Are the YOLO-layers simply ignored during translation

### ISSUE THREAD

**Issue by chinmay5** [qqwweee/keras-yolo3#76]
I saw the code for conversion of tiny-yolo. First of all, thank you so much for it. However, I am especially surprised with the lines 
`elif section.startswith('yolo'):
            out_index.append(len(all_layers)-1)
            all_layers.append(None)
            prev_layer = all_layers[-1]`
Are the YOLO layers simply ignored? How is the translation happening in that case then?

**Comment by chinmay5** [comment]
I figured it out. I think the issue can be closed.

**Comment by hl037** [comment]
...But you could have provided some explanations >.<
