### ISSUE TITLE
the box decode

### ISSUE THREAD

**Issue by xiaohu2015** [qqwweee/keras-yolo3#8]
Have you got the reason why 
box_xy = (box_xy + xy_offset + 1) / conv_dims works

**Comment by qqwweee** [comment]
The mistake is that, when stride=2 darknet uses left and top zeropadding, but Conv2D with padding='same' uses right and bottom.

**Comment by xiaohu2015** [comment]
@qqwweee Oh, that is a problem when conv2d with kerel=3x3, stride=2 and padding="SAME". In this case, only 0.5 padding is needed, the padding is not asymmetrical because we can only padding 1 rows and colums either in  right and bottom or left and top. Thanks a lot.

**Comment by gittigxuy** [comment]
@xiaohu2015 ,I have the same question,could you please cite a example to illustrate this problem?
