### ISSUE TITLE
yolo_weights.h5 is different from yolo.h5

### ISSUE THREAD

**Issue by overfitover** [qqwweee/keras-yolo3#80]
Thanks for u code!
when I run train.py without loading pretrained model，I get yolo_weights.h5 whose structure is different from yolo.h5.

**Comment by qqwweee** [comment]
What structure do you mean?

**Comment by overfitover** [comment]
![2018-06-02 19 30 15](https://user-images.githubusercontent.com/38489551/40873936-772e4e22-6658-11e8-8f8b-fe50c68d211b.png)
![2018-06-02 19 30 50](https://user-images.githubusercontent.com/38489551/40873937-7783c0c8-6658-11e8-8246-b5b83be1823e.png)
like this.

**Comment by qqwweee** [comment]
I think it doesn't matter, because only Conv and BN layers have weights that we need. Keras `model.load_weights` can handle this.
