### ISSUE TITLE
about train.py

### ISSUE THREAD

**Issue by simonhandsome** [qqwweee/keras-yolo3#81]
hello, when i run python train.py, it returns error as: type error,load_weights() got 2 argument 'skip_mismatch' argument error, it seems like 'skip_mismatch'returns the argument error,whats the problem, my environment setting as keras version:2.1.5, pls help,tks,by simon

**Comment by qqwweee** [comment]
You can reinstall Keras and try again.

**Comment by simonhandsome** [comment]
hi,i've reinstall keras 2.1.5 for more times,but it doesnt seem to solve the problem

**Comment by qqwweee** [comment]
Is there more than one Python environment in your pc? Keras 2.1.5 works fine.

**Comment by simonhandsome** [comment]
tks,it works, and do you know how to using keras model to train on different size of images??

**Comment by qqwweee** [comment]
What do you mean about different size? The different sizes are usually preprocessed to a fixed size. And that's what we already do.

**Comment by simonhandsome** [comment]
I want to train on different images  with unet model, do you know ow to build the model and put different input shape of images into the model to train??

**Comment by qqwweee** [comment]
Sorry but I don't know U-net. Since U-net is a fully convolutional network, it is similar to YOLOv3. Just set the height and width of input layer to None.

**Comment by simonhandsome** [comment]
i've set it to none,but it says the wrong shape,i think its my training set with wrong image shape,btw,do you know how to store different size of images into array to form a training dataset in python?

**Comment by qqwweee** [comment]
An array with different wh is not workable. Try `model.fit_generator` and use a date generator to generate arrays one by one. You only have to guarantee the images in one array have the same size. In particular, set batch size to 1. I don't know if this is what you need or not.

**Comment by simonhandsome** [comment]
ok,tks,i'll try it,and one more question,can i install both gpu drivers on both systems to run gpu on windows and ubuntu?
or can just install it on one system??
tks for reply, by Simon~

**Comment by qqwweee** [comment]
I'm not sure but I think the system is independent.
