### ISSUE TITLE
train done on VOC2007  but python yolo.py  ERROR

### ISSUE THREAD

**Issue by lyxlty** [qqwweee/keras-yolo3#83]
HELLO! I python train.py  on datasets VOC2007, train done,I have got my_yoloweights ,I only modify model weights path in  yolo.py ,but when I python yolo.py encounter problems:

 ValueError: Dimension 0 in both shapes must be equal, but are 1 and 75. Shapes are [1,1,1024,255] and [75,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [75,1024,1,1].
@qqwweee thanks~~~

**Comment by qqwweee** [comment]
Change class path to voc class as well.

**Comment by lyxlty** [comment]
@qqwweee THANS! I do the same as your voc_annotation.py vocdatasets(2017,train ,) ('2007', 'val'), ('2007', 'test') but the result is not good at forty pic test ;
1、have a picture  undetected; predict box is not accuracy
3、although some picture is easy to recognition but the confidence is a  little low 
4、predict box numbers is less when picture has many objection 
5、How much is the learning rate ,I have not found the learing rate in train.py
6、could you teach me how to  improve the test result,thanks!!!

**Comment by qqwweee** [comment]
@lyxlty Default learning rate is 0.001, see keras.optimizers.Adam for details. I'm afraid I cannot help you because I'm a new learner.
