### ISSUE TITLE
change class_name to 8 classes

### ISSUE THREAD

**Issue by overfitover** [qqwweee/keras-yolo3#84]
I have a problem, when I changed class_name to 8 classes and I set load_pretrained=False, freeze_body=False.
![2018-06-04 11 08 34](https://user-images.githubusercontent.com/38489551/40896566-340a8b12-67a5-11e8-8bc6-e1a18dc1e41e.png)
![2018-06-04 11 07 55](https://user-images.githubusercontent.com/38489551/40896568-38484f0c-67a5-11e8-8f51-9d241757e7da.png)

**Comment by qqwweee** [comment]
The class id in your annotation file should be 0 to 7. There is a 8, which leads to the error.

**Comment by overfitover** [comment]
copy! Thank u very much.

**Comment by overfitover** [comment]
your code is so good.Could you give me some advice for learning keras?

**Comment by qqwweee** [comment]
Not a piece of advice. I usually read Keras documentation or Keras python help, when I meet problems.
