### ISSUE TITLE
How can I pretrain my own data and then re-train

### ISSUE THREAD

**Issue by franklu323** [qqwweee/keras-yolo3#88]
Hi, I'm new to the deep learning.
I saw you updated your code and right now it can use the original pretrained weights.
I'm confused about, how can I use my own data to do the pretrain  and get its weights then use my pretrained weights to re-train my model? Is this possible?
Thank you so much

**Comment by qqwweee** [comment]
The original pretrained weights, you say, darknet53 weights, is used for classification task. What we usually do is to load it on our detection model then start training. There is no need, and it is not recommended, to train a newly initialized model. So don't pretrain on your own data, use darknet53 weights or yolo weights.

**Comment by zq1314** [comment]
hi ,if I want to use the original pretrained weights,should I set the freeze_body=False? @qqwweee

**Comment by franklu323** [comment]
Thanks for the reply, now I'm using  yolo_weights.h5 training the model. However, when I start train.py, it shows  "Freeze the first 249 layers of total 252 layers." And the picture is shown as 
![default](https://user-images.githubusercontent.com/28680833/41020625-b77d1370-69b7-11e8-8d01-cb4b5e07ec44.PNG) What is 1/33 means?? 
Because in your previous code, when I trained the model, it had [1/1198] to [1198/1198] (I have 1198 samples) and stride 32 for each step.
I'm confused about this difference. @qqwweee

**Comment by qqwweee** [comment]
@zq1314 you shouldn't freeze 249 layers when you only load darknet53 weights (184 layers in Keras). It is perhaps a good way to freeze 184 layers first and then unfreeze them. I am trying and haven't got a useful result yet.

@franklu323 the previous one counts by samples and the present one counts by steps. It doesn't matter at all.
