### ISSUE TITLE
Modified to save predicted objects every 2 seconds to be used as training data

### ISSUE THREAD

**Issue by zubairahmed-ai** [qqwweee/keras-yolo3#9]
Please see here https://github.com/zubairahmed-ai/yolov3

**Comment by tanakataiki** [comment]
Do you mean to save every 2 second of JPEGImage and get annotation file of voc format automatically？

**Comment by zubairahmed-ai** [comment]
Nope. Just all identified objects as images every two seconds. It is not perfect yet and has its flaws that I'm working on

**Comment by zubairahmed-ai** [comment]
Now it works fine, it also doesn't repeatedly saves stationary objects (like parked car) and tries not to even draw border around it

**Comment by tanakataiki** [comment]
Good luck
