### ISSUE TITLE
support for training images with no label/bbox

### ISSUE THREAD

**Issue by n-edelman** [qqwweee/keras-yolo3#90]
Hi I'm trying to train this implementation on my own data. I have some images that have no label at all/no bbox annotation. After looking thru train.py, I believe there is no support for training images w/o labels. Am I correct in this assumption? 

Also, if I am correct, is support for this expected at any point? It would be a nice to have, and I would be interested in contributing if other people want this support as well.

Thanks

**Comment by qqwweee** [comment]
Thanks for your enthusiasm. I have done this and will push it later.

**Comment by n-edelman** [comment]
wonderful, thank you!
