### ISSUE TITLE
problems  in train.py 

### ISSUE THREAD

**Issue by xm1112** [qqwweee/keras-yolo3#91]
Load weights model_data/yolo_weights.h5.
Freeze the first 249 layers of total 252 layers.
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    _main()
  File "train.py", line 33, in _main
    train(model, annotation_path, input_shape, anchors, len(class_names), log_dir=log_dir)
  File "train.py", line 48, in train
    with open(annotation_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'train.txt'

i can't found train.txt
how to solve it? thanks!

**Comment by qqwweee** [comment]
`train.txt` is your annotation file which defines your dataset. You need to generate it first.

**Comment by xm1112** [comment]
thanks you !!!  
I used the voc2007 dataset to train, generated 3 txt files, and then ran Yolo.py with my trained weight file, which showed errors.
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 75. Shapes.

I think, what is not changed in the Yolo file?

**Comment by xm1112** [comment]
thanks you !!!
I used the voc2007 dataset to train, generated 3 txt files, and then ran Yolo.py with my trained weight file, which showed errors.
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 75. Shapes are [1,1,1024,255] and [75,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [75,1024,1,1].

**Comment by xm1112** [comment]
thank you !!!
Is there any difference between the two sentences？
python convert.py yolov3.cfg yolov3.weights model_data/yolo.h5
python convert.py -w yolov3.cfg yolov3.weights model_data/yolo_weights.h5

They are all using the yolo3.cfg

**Comment by qqwweee** [comment]
One is Keras model file, and another Kerea weights file.

**Comment by xm1112** [comment]
Thank you very much!!!!!!
Only loss is displayed on tensorboard. Do you have the code of accuracy evaluation such as MAP and recalll?

**Comment by franklu323** [comment]
Hi, do you know what is 'freeze'? When I train my model , it shows me 'Freeze the first 249 layers of total 252 layers'. But in the train.py (from lane 55), it said 'Unfreeze and continue training, to fine-tune'. I'm wondering how can I do this.
Thank you so much. @qqwweee

**Comment by qqwweee** [comment]
@xm1112 no.

@franklu323 'freeze' means not updating the weights.

**Comment by xm1112** [comment]
Before it can be run, again run time, prompt no keras, how to solve?

**Comment by Sivabanu** [comment]
How to get yolo anchors text file
