### ISSUE TITLE
What's the input node and output node prefix of this model? 

### ISSUE THREAD

**Issue by tonnkie** [qqwweee/keras-yolo3#94]
I want to translate the h5 file to pb file, so that I could use it in tensorflow.
Many Thanks.

**Comment by qqwweee** [comment]
I don't know that. Does tensorboard graph help?

**Comment by shenyingying** [comment]
> I want to translate the h5 file to pb file, so that I could use it in tensorflow.
> Many Thanks.

have you resolve this question,it occurs to me ,thanks

**Comment by zhoujinhai** [comment]
> I want to translate the h5 file to pb file, so that I could use it in tensorflow.
> Many Thanks.

How to test the pb file in tensorflow?
